getsentry/sentry-rust

- src/lib.rs
Right now, this will only encode strings up to the first escape character, and it won't encode anything at all if no escape characters are found.
That is to say, currently `"foo".to_owned().to_json_string()` returns `""`, and `"foo\" bar".to_owned().to_json_string()` returns `"foo"`.
> Fix ToJsonString

- src/lib.rs
looks like sentry doesn't like loggers that have spaces in them. We should instead put the file/line in the "culprit" field. the sentry UI seems to like it when you use the culprit field, as it sticks its contents right below the name of the message.
> make event fields work a little better

- Cargo.toml
- src/lib.rs
> include stack trace in event

- src/lib.rs
This patch adds the ability to use custom tags. I wasn't sure whether I should add a new argument to `Event::new` or a new method to `Event`, so I ended up with a method. If you prefer otherwise then I'll change it. I also added a public method to posting an `Event` to Sentry and fixed the serialization of tags.
> Add push_tag to Event (fix #7)

- Cargo.toml
- src/lib.rs
hyper 0.10 does not support HTTPS natively.
Related issue:
https://github.com/hyperium/hyper/issues/1009
> Use hyper-native-tls for https

- src/lib.rs
Fixes #15.
When I turned logging to the trace level, I saw this:
```
Sentry body {"event_id":"","message":"Panic Handler Testing","timestamp":"2017-06-04T16:51:23","level":"fatal","logger":"panic","platform":"other","sdk": {"name":"rust-sentry","version":"0.1.9"},"device": {"name":"","version":"","build":""},"culprit": "src/lib.rs: 829","server_name":"Server Name","release":"release","environment":"test_env","stacktrace":{"frames":[{"filename":"","function":"_pthread_start","lineno":0},{"filename":"","function":"_pthread_body","lineno":0},{"filename":""/Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libstd/sys_common/thread.rs"","function":"std::sys::imp::thread::{{impl}}::new::thread_start","lineno":21},{"filename":""/Users/rustbuild/src/rust-buildbot/slave/stable …
```
> fix doubly escaped filenames in stacktrace breaking JSON body

- Cargo.toml
- src/client/real.rs
This allows to parse the following names:
```
futures::task_impl::std::set
_<futures..task_impl..Spawn<T>>::enter::_{{closure}}
```
> fix(client): Parse crate names from impl traits

- .travis.yml
- Cargo.toml
- Makefile
- src/backtrace_support.rs
- src/utils.rs
- `tokio` requires `crossbeam-deque`, which will only compile on 1.21.0
- `finshlibs` depends on `bindgen` (which it probably shouldn't), which in turn requires `bitflags` and that requires 1.20.0
> ci: Compatibility with rust 1.21.0

- Cargo.toml
- src/client/real.rs
Allows default contexts to be merged into an event even when the _scope_ parameter is set to `None`. Also, the `CONTEXT_DEFAULTS` object is now accessed more lazily (only when the entry is really vacant).
Note that this required an update to `sentry-types 0.5.3` for the `protocol::map::Entry` import.
> fix(client): Merge default contexts without scope

- examples/log-demo.rs
- src/integrations/log.rs
This adds support for specially also handling warnings. It also adds some missing tests.
This helps cases like in #46. I do not want other levels here due to the backtrace we're attaching and the cost associated with it.
> feat: Added support for emitting warning issues in log integration

- README.md
The [current link](https://crates.io/crate/sentry) is broken with the error "Oops, that route doesn't exist!". The correct link uses `crates` instead of `crate` in the path.
> Fix wrong crates.io link in the README

- Cargo.toml
- src/hub.rs
- src/lib.rs
This switches to the fragile library to handle non send processors and solves potentially UB.
> feat: Switch to fragile library for non send handling

- README.md
Fixes https://github.com/getsentry/sentry-rust/issues/55
> meta(readme): Update the beta disclaimer

- appveyor.yml
- examples/error-chain-demo.rs
- src/api.rs
- src/client.rs
- src/test.rs
- src/transport.rs
- tests/test_basic.rs
- tests/test_client.rs
This simplifies the API in that one can explicitly set the DSN to `None` now
on the options to get a disabled client.  All that other API surface just
goes away.  As a followup the transport will also move into the options.
> feat: Add dsn to options and deprecate disabled methods

- examples/before-send.rs
- src/client.rs
- src/lib.rs
- src/macros.rs
- src/scope/real.rs
- src/transport.rs
This solves an issue that mozilla ran into where the guard was dropped too early and the transport closed. That means events are quietly discarded.
> feat: Added debug logs and must use flag for init

- Cargo.toml
- src/integrations/failure.rs
> Updated `failure` integration for new backtrace display

- src/api.rs
- src/hub.rs
This is just a shot in the dark here, but in a default client usage `with_scope` always takes the second, non-hub code path, so I figure this might be the reason.
> Fix with_scope

- src/integrations/failure.rs
- src/integrations/panic.rs
It would be useful to have a way to turn a `failure::Error` into a panic without losing the backtrace.
This is very common when you receive an error from further down the call-stack, and you don't have a good way to handle it, but currently you only get a callstack to the panic location, you lose the underlying error's backtrace.
This is just one possible way to implement the functionality.
> Combined panic/failure integration

- Cargo.toml
- README.md
- build.rs
- examples/before-send.rs
- examples/error-chain-demo.rs
- examples/event-processors.rs
- examples/failure-demo.rs
- examples/init-with-client.rs
- examples/log-demo.rs
- examples/message-demo.rs
- examples/panic-demo.rs
- examples/send-with-extra.rs
- examples/thread-demo.rs
- integrations/sentry-actix/Cargo.toml
- integrations/sentry-actix/examples/basic.rs
- integrations/sentry-actix/src/lib.rs
- src/backtrace_support.rs
- src/client.rs
- src/constants.rs
- src/hub.rs
- src/integrations/failure.rs
- src/integrations/log.rs
- src/integrations/panic.rs
- src/lib.rs
- src/macros.rs
- src/scope/noop.rs
- src/scope/real.rs
- src/test.rs
- src/transport.rs
- src/utils.rs
Since some of our dependencies require Edition 2018 now, I figure we could upgrade right away.
> ref: Upgrade to Rust Edition 2018

- Cargo.toml
- src/utils.rs
This skips over non code segments. Support for this was added in 0.4.1.
> feat: Update to newer findshlibs that resolves issues on linux

- src/integrations/log.rs
- Default value is true to be backward compatible.
- The new field will cause compiler error if LoggerOptions is instantiated without defaults. The possible fix is very simple and straightforward but a version bump is still needed.
> Add configuration to disable expensive computations of stacktraces.

- Cargo.toml
- Makefile
- src/lib.rs
- src/transport.rs
- src/utils.rs
This pull request provides two features: disabling all built in transports
and using curl as an optional transport instead of reqwest.
This should cut down on a lot of extra dependencies for users that do not
want to pull in all of tokio.
> feat: Support for curl and disabled transports

- .gitignore
- src/transport.rs
- Sharing through Arc is implemented only for Reqwest client that can be shared among threads.
- Curl client is not thread safe so it would require a mutex.
```
sentry::ClientOptions {
transport: Box::new(|options: &sentry::ClientOptions| -> Box<sentry::internals::Transport> {
Box::new(ReqwestHttpTransport::new(options, Some(http_client)))
}),
// ...
}
```
> #130 Possibility to share Reqwest client with Sentry through `transport` config.

- Cargo.toml
This issue is related to #88 and would prevent issues like it when
openssl 1.2 comes out.
Currently, sentry-rust depends on reqwest with default feature flags,
which pulls in `native-tls` and `openssl`.
This causes multiple issues:
1. On systems without openssl header packages installed, openssl-sys
won't build.
2. If distributions like arch linux update to newer versions of openssl,
issues like #88 will arise
3. Systems that don't support openssl are not supported (although
targeting embedded systems with non-unix OSes is probably not a goal
in this project)
This commit adds support for building reqwest with rustls support, using
the new feature flag ~~`rustls`~~ `with_rustls`.
This fixes #136.
> feat: add support for openssl-less builds

- src/backtrace_support.rs
- src/client.rs
- src/integrations/failure.rs
**TL;DR:** We need to resume the work on exposing `failure::Backtrace` internals.
Backtrace parsing for recent versions of `backtrace-rs` fails to obtain inline frames. The regular expression is now tidied up a little bit and supports both the old and new backtrace format in one go, along with inline frames. 
Additionally, crate name parsing was broken for the new Rust mangling schema, which no longer uses underscores in front of trait implementors and uses `::` instead of `..` for crate separators.
> fix(backtrace): Support newer backtrace format

- src/macros.rs
I've got a couple of projects that require nightly and I've started to get a deprecation warning for `std::sync::ONCE_INIT`. Docs confirm it'll be marked from 1.38 ([link](https://doc.rust-lang.org/nightly/std/sync/constant.ONCE_INIT.html)).
`Once::new()` has been around since 1.20 and since this library claims to require at least 1.31 I figured I'd be safe to switch.
> Stop using std::sync::ONCE_INIT

- .travis.yml
- README.md
- integrations/sentry-actix/README.md
- src/transport.rs
Good bug.
The curl transport implementation works like this:
- Serialize the event into an in-memory buffer
- Determine the length of the buffer and let curl read it
- In the read function, pass a chunk into the buffer
However, the read function always sliced the beginning of the buffer, rather than reading it chunk by chunk. This is fixed by wrapping the buffer into a cursor, which implements read correctly.
> fix(curl): Do not loop the same data when sending with curl

- .travis.yml
- Cargo.toml
- README.md
- build.rs
- integrations/sentry-actix/README.md
- integrations/sentry-actix/src/lib.rs
- src/backtrace_support.rs
- src/client.rs
- src/integrations/env_logger.rs
- src/integrations/failure.rs
- src/integrations/log.rs
- src/lib.rs
- src/transport.rs
- src/utils.rs
- tests/test_basic.rs
- tests/test_client.rs
- tests/test_log.rs
- tests/test_processors.rs
Note that this is a minimal effort to bring `sentry-rust` up to speed. We will be looking into trimming it down and adding more integrations at a later point.
Fixes #156
Fixes #159
Fixes #171
Fixes #182
> build: Update most dependencies

- src/integrations/env_logger.rs
- src/integrations/log.rs
These now match the default enabled/disabled state defined in `Cargo.toml` and the top level documentation.
> Updated documentation of default enabled/disabled of integrations

- Cargo.toml
- README.md
- sentry-actix/README.md
- sentry-types/CHANGELOG.md
- sentry-types/Cargo.toml
- sentry-types/README.md
- sentry-types/src/auth.rs
- sentry-types/src/dsn.rs
- sentry-types/src/lib.rs
- sentry-types/src/macros.rs
- sentry-types/src/project_id.rs
- sentry-types/src/protocol/mod.rs
- sentry-types/src/protocol/v7.rs
- sentry-types/src/utils.rs
- sentry-types/tests/test_auth.rs
- sentry-types/tests/test_protocol_v7.rs
- sentry/Cargo.toml
This imports the whole sentry-types repo, including all its history.
This was done using:
```
git remote add types https://github.com/getsentry/rust-sentry-types.git
git fetch types master
… move things into the sentry-types directory, delete everything unrelated …
git commit --all
git checkout -b types-head
git checkout master
git merge types-head --allow-unrelated-histories
```
> meta: Import sentry-types into the monorepo

- sentry-core/src/api.rs
- sentry-core/src/backtrace_support.rs
- sentry-core/src/breadcrumbs.rs
- sentry-core/src/client.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/hub.rs
- sentry-core/src/lib.rs
In particular: `ClientOptions` and `IntoBreadcrumbs` into its own file, and some stacktrace utils into
the `stacktrace_support` file.
> ref: Move a few things into separate files

- sentry-core/src/client.rs
- sentry-core/src/lib.rs
- sentry-core/src/macros.rs
- sentry/Cargo.toml
- sentry/src/init.rs
- sentry/src/lib.rs
This is in preparation of moving the default options to the sentry
crate as well, which is needed to move the default transport and
integrations out of `sentry-core`.
Along with this, it removes some deprecated functions.
> ref: Move the init function to sentry crate

- sentry-core/src/backtrace_support.rs
- sentry-core/src/integrations/failure.rs
I was reading the code for unrelated questions and noticed this.
Regarding `filename` I feel it's better to just return an `&str` when you can and let the caller convert *if needed*.
This is semver compatible (since `filename` ends up not being exported).
> Remove some unnecessary allocations

- sentry-core/Cargo.toml
findshlibs 0.5.0 has a serious defect in `SharedLibrary::id`, where it
uses file sizes and offsets when examining the PT_NOTE sections of an
ELF binary instead of the memory size/offset fields. This issue was
corrected by gimli-rs/findshlibs@046a431, but was released along with a
couple of semver breaking changes so it needs a bump in Cargo.toml to be
picked up.
This has a fairly major impact on projects where you have `with_debug_meta` enabled,
as it can lead to all sorts of issues, ranging from at best corrupted crash uploads reaching
Sentry, to SEGFAULTs when a thread panics, to wild UB as we try and read from totally
random memory addresses.
We have tested this in production by patching `findshlibs` with Cargo's patch function.
I'd suggest pushing out a 0.18.1 release for this if …
> Bump findshlibs to 0.7.0

- Cargo.toml
- sentry-anyhow/Cargo.toml
- sentry-anyhow/src/lib.rs
- sentry/Cargo.toml
- sentry/examples/anyhow-demo.rs
Unfortunately, it does require a separate integration/method, since
`anyhow::Error` does not impl `std::error::Error`.
> feat: Add anyhow Integration

- Cargo.toml
- rustfmt.toml
- sentry-slog/Cargo.toml
- sentry-slog/src/converters.rs
- sentry-slog/src/drain.rs
- sentry-slog/src/integration.rs
- sentry-slog/src/lib.rs
This Integration consists of both an `Integration` part, as well as a
`Drain` part.
The Integration can be configured with custom filters and mappers.
fixes #160 
closes #161 
closes #172
> feat: Add a `slog` Integration

- sentry/Cargo.toml
- sentry/src/lib.rs
- sentry/src/transport.rs
This PR provides support of [surf](https://github.com/http-rs/surf) HTTP client as an alternative to reqwest and curl.
> feat: Add support for surf HTTP client

- Makefile
- sentry-actix/Cargo.toml
- sentry-core/Cargo.toml
- sentry-core/src/api.rs
- sentry-core/src/client.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/hub.rs
- sentry-core/src/integration.rs
- sentry-core/src/lib.rs
- sentry-core/src/macros.rs
- sentry-core/src/scope/mod.rs
- sentry-core/src/test.rs
- sentry-error-chain/src/lib.rs
- sentry/Cargo.toml
- sentry/examples/anyhow-demo.rs
- sentry/examples/error-chain-demo.rs
- sentry/examples/failure-demo.rs
- sentry/examples/log-demo.rs
- sentry/examples/thread-demo.rs
- sentry/src/defaults.rs
- sentry/src/lib.rs
- sentry/src/transport.rs
- sentry/tests/test_basic.rs
- sentry/tests/test_client.rs
- sentry/tests/test_log.rs
- sentry/tests/test_processors.rs
Cleans up the feature flags of `sentry-core`, but tries to keep the existing feature flags of `sentry`, for backwards compatibility. Not quite sure if we want to do that, or rather just remove the non-default features, and rename the others.
> ref: Clean up the feature flags a bit

- Cargo.toml
- sentry-actix/src/lib.rs
- sentry-anyhow/src/lib.rs
- sentry-core/Cargo.toml
- sentry-core/src/api.rs
- sentry-core/src/breadcrumbs.rs
- sentry-core/src/client.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/error.rs
- sentry-core/src/futures.rs
- sentry-core/src/hub.rs
- sentry-core/src/integration.rs
- sentry-core/src/intodsn.rs
- sentry-core/src/lib.rs
- sentry-core/src/macros.rs
- sentry-core/src/scope/real.rs
- sentry-core/src/test.rs
- sentry-debug-images/src/unix.rs
- sentry-error-chain/src/lib.rs
- sentry-failure/src/lib.rs
- sentry/src/defaults.rs
- sentry/src/lib.rs
- sentry/src/transport.rs
- sentry/tests/test_basic.rs
- sentry/tests/test_client.rs
The `sentry-core` exports have been a bit restructured, other things in
`sentry` have been marked as deprecated.
> ref: Restructure and document the public core API

- sentry-debug-images/src/unix.rs
This ports over the logic from [`symbolic`](https://github.com/getsentry/symbolic/blob/4d509d112f385daa1ec11a78e4b815e54b0dd3b6/debuginfo/src/elf.rs#L383) to compute `DebugId` from the GNU build identifier. This fixes two distinct bugs:
1. A panic if the identifier is smaller than 16 bytes (Fixes https://github.com/getsentry/sentry-rust/issues/220)
2. Incorrect endianness on big-endian targets.
> fix(debug-images): Compute correct DebugId for ELF images

- sentry-core/src/api.rs
- sentry-core/src/client.rs
- sentry-core/src/constants.rs
- sentry-core/src/hub.rs
- sentry-log/src/integration.rs
- sentry-log/src/logger.rs
- sentry-panic/src/lib.rs
- sentry-slog/src/drain.rs
- sentry/src/defaults.rs
- sentry/src/lib.rs
This also exposes a new global `with_integration` function which is also
used in existing integrations.
> fix: Better document default integrations

- CHANGELOG.md
- Makefile
- sentry-actix/Cargo.toml
- sentry-contexts/src/integration.rs
- sentry-contexts/src/lib.rs
- sentry-core/src/lib.rs
- sentry-core/src/macros.rs
- sentry-types/CHANGELOG.md
- sentry-types/src/protocol/mod.rs
- sentry/Cargo.toml
- sentry/src/lib.rs
- sentry/src/transport.rs
* Updates the main documentation.
* Renames the transport-related feature flags.
* Drafts a changelog highlighting the breaking changes.
> meta: Draft a changelog and update docs/features

- .craft.yml
Configure craft to remove circular dev-dependencies before publishing the crate. This requires `cargo-hack` on the publishing system. 
Requires https://github.com/getsentry/craft/pull/112
> build(craft): Strip dev dependencies before publishing

- sentry-panic/src/lib.rs
The "handled" prop of the exception mechanism is used in some places, for example the upcoming release health feature that will flag sessions as "crashed" if they are not handled.
> fix: Add an unhandled mechanism to panics

- sentry-core/src/client.rs
- sentry-core/src/hub.rs
- sentry-log/src/integration.rs
This should fix #237, and we should backport this to 0.19 as well.
> fix: Deal with concurrent hub access better

- sentry-contexts/src/lib.rs
0.19.0 made the utility functions in context private, but they were quite useful when using `sentry-contrib-native` to get the same information as the Rust SDK eg.
```rust
if let sentry::protocol::Context::Device(dev) =
sentry::integrations::contexts::utils::device_context()
{
let mut dev_ctx = Vec::new();
ser!(dev_ctx, dev, [name, family, model, model_id, arch]);
dev_ctx.push(("type", "device"));
sentry_native::set_context("device", dev_ctx);
}
```
> Make contexts::utils public

- .github/workflows/ci.yml
macOS check and test jobs fail with a super strange `error[E0463]: can't find crate for `serde_derive` which `chrono` depends on` error which even happens when re-running previously green runs.
> ci: Work around CI cache corruption on macOS

- sentry-core/Cargo.toml
- sentry-core/src/api.rs
- sentry-core/src/client.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/envelope.rs
- sentry-core/src/hub.rs
- sentry-core/src/lib.rs
- sentry-core/src/scope/noop.rs
- sentry-core/src/scope/real.rs
- sentry-core/src/session.rs
- sentry/examples/health.rs
- sentry/src/init.rs
- sentry/src/transport.rs
This adds release health sessions to the SDK, with some things that require special attention:
* sessions live on the scope.
* sessions are forward-inherited, which means that creating a new Hub from another one, and pushing scopes will use the exact same session.
* however, sessions are not backward-inherited, which means that starting a new session will not propagate backwards to any parent scopes/hubs.
So far, intermediate session updates are sent along with normal events, however session end updates are sent on their own and not yet batched together. This means that request-mode sessions are not yet as efficient as we would like them to be.
> feat: Add basic session support

- sentry-core/src/scope/real.rs
- sentry/tests/test_basic.rs
The [Unified API](https://develop.sentry.dev/sdk/unified-api/) docs specify a function on the scope for clearing all current breadcrumbs. This is an implementation of that.
> Add scope.clear_breadcrumbs()

- sentry-core/Cargo.toml
- sentry-core/src/scope/real.rs
(that fix was simple and not at all obvious)
Closes #253
> chore: Update to use `im 15.0.0`

- sentry-core/src/client.rs
- sentry/Cargo.toml
- sentry/src/transport.rs
The synchronization fixes have been proposed in #172 originally
> fix: Improve transport synchronization and consume response

- CHANGELOG.md
- sentry-backtrace/src/trim.rs
- sentry-core/src/lib.rs
- sentry-error-chain/src/lib.rs
- sentry-types/src/auth.rs
- sentry/Cargo.toml
- sentry/examples/error-chain-demo.rs
- sentry/src/defaults.rs
- sentry/src/lib.rs
This also officially deprecates the `error_chain` integration.
> ref: Remove deprecated feature flags and items

- .github/workflows/ci.yml
I spent the weekend to create a rust-tailored cache action which will:
* cache the registry index, registry cache and target folder separately and with sensible cache/restore keys
* sets `CARGO_INCREMENTAL=0`
* cleans the registry cache and target folder to only include *needed dependencies*, thus avoiding infinite cache buildup
(this means that even noop builds will still completely rebuild *workspace crates*)
* also includes the macos cache corruption workaround
> ci: Use smarter cache action

- .github/workflows/ci.yml
turns out, changing RUSTFLAGS invalidates all the caches, thats why the `checkfast/fastfast` job was not using it properly.
> ci: Make testfast actually fast

- sentry-anyhow/Cargo.toml
- sentry-anyhow/src/lib.rs
- sentry-contexts/src/integration.rs
- sentry-contexts/src/lib.rs
- sentry-core/src/hub.rs
- sentry-core/src/lib.rs
- sentry-debug-images/src/integration.rs
- sentry-debug-images/src/lib.rs
Not really sure if I should deprecate these first, or just break them right away. I don’t think people use these integrations directly a lot.
> ref: Deprecate public fields on Integrations

- sentry-core/src/client.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/session.rs
- sentry-types/src/protocol/envelope.rs
- sentry/src/init.rs
The flusher maintains a queue that is flushed every minute.
Sessions are batched into Envelopes at this point, but in the future
might be pre-aggregated.
> ref: Introduce a SessionFlusher

- sentry-core/src/scope/real.rs
- sentry-types/src/protocol/envelope.rs
- sentry-types/src/protocol/v7.rs
Hello! I'm the lead developer at [Wavy Labs Inc.](https://github.com/WavyLabs/) We're integrating Rust more and more into our stack and we've been using Sentry for over a year. We'd love to start integrating Performance Monitoring, but it seems this SDK doesn't support it yet.
I'd like to kickstart the discussion on this and contribute some developer time for this. I've been reading the [Guidelines for Tracing Support](https://develop.sentry.dev/sdk/unified-api/tracing/) and peeking into the Python SDK for reference. I've started some preliminary work on adding the new types (Span and Transaction), but I'll need some guidance on integrating with Hub. Feel free to start reviewing at any time!
> Preliminary work to integrate Performance Monitoring 

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- sentry-actix/Cargo.toml
- sentry-actix/README.md
- sentry-actix/examples/basic.rs
- sentry-actix/src/lib.rs
- sentry/Cargo.toml
I refactored the middleware by basing it on 'official' v3 middleware (logger, cors, etc.) Some of the Sentry implementation was re-used from https://github.com/mozilla-services/autopush-rs/blob/9b93817776bb7c8f27383185a1b5ce08607a6b35/autoendpoint/src/middleware/sentry.rs (v2.0 middleware, adapted for v3.0 and `wrap`-style middleware).
Example is updated and tested locally.
Bumped minimum Rust version to 1.42.0 because that's what actix-web 3.0 targets.
Resolves #143
> feat: actix-web 3 support

- sentry-actix/src/lib.rs
Client errors (4xx) should not be captured in the sentry-actix integration.
> fix: sentry-actix should not capture client errors

- sentry-actix/src/lib.rs
Configure the transaction name in the actix middleware at the `scope` level, instead of the event processor.
This fixes the middleware overriding the transaction name when capturing events, and allows users to set a different transaction in scope and sub-scopes.
> fix: scope transaction name can be overriden in sentry-actix

- CHANGELOG.md
- sentry-core/src/api.rs
- sentry-core/src/client.rs
- sentry-core/src/hub.rs
- sentry-core/src/session.rs
This adds the `end_session_with` global and Hub functions that allow
providing an explicit `SessionStatus`.
> feat: End sessions with explicit status

- sentry-anyhow/src/lib.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/hub.rs
- sentry-core/src/scope/real.rs
- sentry-core/src/session.rs
- sentry-panic/src/lib.rs
- sentry/src/defaults.rs
- sentry/src/lib.rs
This adds more documentation for how to use integrations and uses much
more intra-doc links.  The Hub documentation as well as the anyhow
integration documentation have also seen various improvements.
The docs no build again without any warnings.
> docs: Document integrations and the Hub better

- CHANGELOG.md
- sentry-core/src/clientoptions.rs
- sentry/src/defaults.rs
I basically broke this in https://github.com/getsentry/sentry-rust/pull/280
> fix: Correctly apply environment from env

- sentry-slog/Cargo.toml
- sentry-slog/src/converters.rs
Pretty straightforward - adds a wrapper for `Map` that lets it be used as a `slog::Serializer`, which `KV`s can be appended too.
This also enables the `nested-values` feature on `slog` so that it can accept any serde-serializable values. Considered adding a feature flag, but `sentry-core` already pulls in `serde` & co, so it wouldn't really save any dependencies.
> Add slog KVs to the Sentry Map

- sentry-core/src/session.rs
We encountered a really strange panic (reported in Sentry, yay!), unfortunately the only information was
`overflow when subtracting durations, file: library\core\src\time.rs:895:31, thread: sentry-session-flusher`
And, AFAICT, this is the only place in that thread that dues a Duration subtraction, so putting this as a tentative workaround for it.
> Avoid overflow panic

- CHANGELOG.md
- sentry-log/src/converters.rs
- sentry-slog/src/converters.rs
- sentry-slog/src/lib.rs
Valid exception records in Sentry require a type that reflects the exception name, and frames with function names. Otherwise, issue grouping cannot work properly.
> fix(log): Create a plain message for exception logs

- sentry-backtrace/src/integration.rs
Noticed that these were getting missed in processing.
> Process thread stacktraces in addition to exception traces

- .github/workflows/ci.yml
- README.md
- sentry-core/Cargo.toml
- sentry-core/src/futures.rs
- sentry/Cargo.toml
This upgrades `sentry-core` and `sentry` to the new releases. `sentry-actix` is still based on `tokio 0.2`. The MSRV is bumped to 1.45.0.
> Upgrade to `tokio 1.0` and `reqwest 0.11`

- sentry-core/Cargo.toml
- sentry-core/benches/scope_benchmark.rs
The benchmarks so far test the scope with tags and breadcrumbs in a few
situations:
* inactive client,
* active client, only scope manipulation
* active client, scope and capturing messages
The Benchmarks also allow measuring the "minimal API" mode, which
basically removes the complete implementation at compile time.
Measurements on my system are:
Minimal API (compile-time noop): ~2.6ns
Tags:
* inactive: 66ns
* active: 26us
* capture: 53us
Breadcrumbs:
* inactive: 2us
* active: 52us
* capture: 88us
> meta: Add a small benchmark suite to sentry-core

- sentry-core/Cargo.toml
- sentry-core/benches/scope_benchmark.rs
- sentry-core/src/hub.rs
- sentry-core/src/scope/real.rs
This incurs a lot more cloning when using lots of scopes and breadcrumbs for example.
fixes #258
> fix: Remove abandoned `im` crate in favor of Arc::make_mut

- sentry-actix/Cargo.toml
- sentry-actix/examples/basic.rs
- sentry-actix/src/lib.rs
- sentry-core/Cargo.toml
- sentry-core/src/client.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/lib.rs
- sentry-core/src/session.rs
- sentry-types/src/protocol/envelope.rs
- sentry-types/src/protocol/session.rs
- sentry/src/init.rs
This should work together with https://github.com/getsentry/relay/pull/815
> feat: Add support for pre-aggregated Sessions

- sentry-core/src/client.rs
- sentry-panic/src/lib.rs
This is a followup to #314 which I apparently forgot to push.
> fix: Expose flush method and use it in the panic hook

- .codecov.yml
- .github/workflows/ci.yml
- README.md
This uses the experimental nightly-only source-based code coverage based on llvm tooling.
Uses my own https://github.com/Swatinem/fucov github action to orchestrate all the steps. That repo has links to some tracking issues. Especially getting coverage for doctests is still broken in workspaces, which I am tracking.
I think this is good enough to land, and will get automatically better once rust/cargo upstream will get fixed.
> ci: Collect Code Coverage

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- sentry-core/Cargo.toml
- sentry-types/Cargo.toml
The sentry-core crate uses the chrono::DurationRound trait which was
only introduced in chrono 0.4.13.  The sentry-types crate is updated
just to keep the versions in sync.
> fix(deps): correct minium chrono version and MSRV

- sentry-core/src/client.rs
- sentry-core/src/hub.rs
- sentry/Cargo.toml
- sentry/tests/test_client.rs
It seems that doing a thread::join from within the Drop impl of a thread
local THREAD_HUB will deadlock for some reason.
Explicitly joining the background flusher as part of the ClientGuard
Drop does work, and is also more correct, as otherwise the PROCESS_HUB
might keep the worker alive forever.
Fixes #322
> fix: Explicitly drop SessionFlusher

- Cargo.toml
- README.md
- sentry-tracing/Cargo.toml
- sentry-tracing/README.md
- sentry-tracing/src/converters.rs
- sentry-tracing/src/layer.rs
- sentry-tracing/src/lib.rs
- sentry/Cargo.toml
- sentry/examples/tracing-demo.rs
- sentry/src/lib.rs
- sentry/tests/test_tracing.rs
This adds a new integration to `tracing-subscriber`'s registry by providing a `Layer` capable of capturing `tracing` events (and `log` logs) as Sentry Exceptions/Events/Breadcrumbs.
Also, this restores the functionality provided by `sentry-log` when using `tracing-subscriber`, as it installs its own logger to capture `log`'s logs as `tracing` events.
The API is heavily inspired by `sentry-log`, and provides the same methods for matching log/event levels to a sentry type (exceptions/events/breadcrumbs).
> feat(tracing): add tracing-subscriber integration

- sentry-types/src/protocol/v7.rs
- sentry-types/tests/test_protocol_v7.rs
This adds support for reporting events with WASM stack traces when eg. running modules via wasmtime or other runtimes.
> Add missing support for WASM images/frames

- sentry/src/lib.rs
> Remove the deprecated `env_logger` feature

- CHANGELOG.md
- sentry-backtrace/src/integration.rs
- sentry/tests/test_basic.rs
> fix: Honor the attach_stacktrace option when capturing errors

- CHANGELOG.md
- sentry-anyhow/Cargo.toml
- sentry-anyhow/src/lib.rs
- sentry-backtrace/src/parse.rs
This also fixes parsing of backtraces that have both line and column numbers.
fixes #337
> feat: Allow capturing backtraces from anyhow

- sentry-core/src/error.rs
The generic `anyhow::msg` will just `Debug::fmt` the `String` that you feed
it, which results in Error types with leading quotes.
> fix: Work around anyhow::msg not having a proper Debug::fmt

- sentry/Cargo.toml
- sentry/src/lib.rs
- sentry/src/transports/curl.rs
- sentry/src/transports/reqwest.rs
- sentry/src/transports/surf.rs
APIs hidden behind features can now be viewed on docs.rs! All feature-gated modules and structs should be annotated with a note that mentions the specific feature flag needed to use the corresponding API.
This primarily fixes a linter warning regarding a link to a nonexistent integration which was gated behind a feature. There are other small fixes as well, mostly just hooking up links that weren't assigned destinations.
While the doc feature is considered unstable, we're taking advantage of the fact that docs are built with nightly by default.
> docs: Expose feature-gated APIs with doc(cfg)

- sentry-anyhow/Cargo.toml
- sentry-anyhow/src/lib.rs
`backtrace` is an optional feature for `anyhow`. I think `sentry-anyhow` should provide it as optional, too.
> feat: Make anyhow backtrace feature optional

- sentry-types/src/protocol/v7.rs
This pull request adds a `SpanStatus` enumeration to the protocol according to the documentation [Span Interface](https://develop.sentry.dev/sdk/event-payloads/span/)
It also changes `status` field type from `Option<String>` to `Option<SpanStatus>`  for `Span` and `Transaction`.
> Add SpanStatus to the protocol.

- sentry-types/Cargo.toml
- sentry-types/src/protocol/envelope.rs
- sentry-types/src/protocol/v7.rs
There are two main changes here to fix errors displayed on the Sentry dashboard when submitting envelopes using the current `Transaction` struct:
- First the `name` field is renamed to `transaction`, this is technically a semver breaking change although given there is not high-level API to work with transactions yet in the SDK this struct probably doesn't have too many consumers yet. If that proves to be a problem it's always possible to just rename the field at the serde level
- Second, the `span_id` fields are now using a custom serializer to truncate the Uuid string at 16 bytes. I went for the simplest change here again, although it means using the Uuid type for fields that are not in fact holding a full UUID in the wire format. Maybe the span IDs should be either a String (like in …
> Update the Transaction struct to match the transaction payload spec

- sentry-core/src/client.rs
- sentry-core/src/clientoptions.rs
- sentry-tracing/Cargo.toml
- sentry-tracing/README.md
- sentry-tracing/src/converters.rs
- sentry-tracing/src/layer.rs
- sentry-tracing/src/lib.rs
I'm marking this as a draft for now as it builds upon the changes in #349 to submit Transaction data directly to the Client as an Envelope. I'll rebase this branch on master when that other PR gets sorted out. (Edit: PR got merged, I rebased my branch)
Anyway for the actual changes: this builds upon the existing `sentry-tracing` infrastructure, a new filter and 3 mappers to the crate. First is `span_filter`, it is used to select spans that are candidate for transaction collection, then `span_mapper` is called for all spans that pass the filter to create a `protocol::Span`. This Span is expected to only be partially initialized as the `tracing::Span` has only been newly created when the mapper is called, and more informations can be added by mutating the protocol struct when the tracing …
> Add span / transaction collection to sentry-tracing

- sentry/Cargo.toml
The current Cargo.toml enables default-features for surf which uses surf's curl-client.  Since surf contains multiple client backends, the current feature set doesn't provide enough flexibility so that one can use the same HTTP client already in use in other parts of an application.
My project is using the h1-client from surf, and I would like to be able to use just a single HTTP client in my project.  This pull request adds a new feature `surf-h1` specifically to use surf with the h1-client.
It might be reasonable to also add additional features for surf so that the other clients can be enabled, here is a link to the client features in surf:
https://github.com/http-rs/surf/blob/1ffaba8873d49c672a45442bfd69ca53b81ea1cc/Cargo.toml#L24-L47
> feat: add feature for using surf with the h1-client

- sentry-tracing/src/converters.rs
- sentry-tracing/src/layer.rs
- sentry/tests/test_tracing.rs
Before this PR this code had no effect:
```rust
tracing::Span::current().record("field", &"data");
```
> feat: Add support of tracing::Span::record operation for sentry-tracing

- .craft.yml
- sentry-actix/Cargo.toml
- sentry-anyhow/Cargo.toml
- sentry-contexts/Cargo.toml
- sentry-core/Cargo.toml
- sentry-log/Cargo.toml
- sentry-panic/Cargo.toml
- sentry-slog/Cargo.toml
- sentry-tower/Cargo.toml
- sentry-tracing/Cargo.toml
- sentry/Cargo.toml
This way, cargo will not verify the versions when publishing, removing
the need to use `cargo-hack` for publishing.
fixes #374
> fix: Remove versions from local dev-dependencies

- sentry-actix/src/lib.rs
- sentry-core/src/scope/noop.rs
- sentry-core/src/scope/real.rs
- sentry/examples/event-processors.rs
- sentry/tests/test_processors.rs
This also removes the need to manually box the argument to `add_event_processor`.
> ref: Avoid double-indirection through Arc<Box<T>>

- sentry-debug-images/Cargo.toml
Related to: #382
But #382 is a more general problem.
> Upgrade `findshlibs` dependency again: Otherwise it stuck forever when an error is captured

- sentry-contexts/Cargo.toml
- sentry-contexts/src/utils.rs
Pulling in the whole Regex crate with Unicode support enabled is an overkill for taking a few ASCII chars.
I've also added error handling to the sysctlbyname calls.
> Remove dependency on regex

- sentry-types/src/protocol/envelope.rs
- sentry/src/transports/ratelimit.rs
- sentry/src/transports/thread.rs
Parsing of headers and rate limits was implemented, but filtered the
envelope was not so far.
> feat: Implement category-based rate limiting (NATIVE-412)

- sentry-core/Cargo.toml
- sentry-core/src/lib.rs
- sentry-core/src/performance.rs
- sentry-core/src/scope/noop.rs
- sentry-core/src/scope/real.rs
- sentry/examples/performance-demo.rs
This implements a manual performance monitoring API, which tries to follow the unified API spec.
One can start a transaction on its own, or based on a distributed tracing header (or another Span), as well as start new child Spans.
Hooking this up to other external services downstream should be possible via an `iter_headers` that allows attaching the headers to outgoing Http requests.
Spans are recorded as part of the transaction they ultimately belong to on `finish`.
Transactions are being sent to sentry properly when they are being `finish`ed.
A Span can be attached to the scope as the *current* span, and queried via `Scope::set_span/get_span`.
This makes it possible to for example query for distributed tracing headers anywhere in the application, or create a child span anywhere.
The …
> feat: API for manual performance monitoring (NATIVE-309)

- sentry-core/src/performance.rs
- sentry-tracing/src/converters.rs
- sentry-tracing/src/layer.rs
- sentry-types/src/protocol/v7.rs
- sentry/examples/tracing-demo.rs
- sentry/tests/test_tracing.rs
Instead of hand-rolling all the transaction/span manipulation, rather implement it on top of the manual performance monitoring API.
> ref: Rewrite tracing integration in terms of manual API (NATIVE-312)

- sentry-tower/Cargo.toml
- sentry-tower/src/http.rs
- sentry-tower/src/lib.rs
- sentry-types/src/protocol/v7.rs
Based on #395, this creates a new sentry-tower feature, which enables a new tower `Layer`, which will start a new transaction for each Http request, using the incoming headers for distributed trace propagation.
> feat: Add a Http Service integration with trace propagation (NATIVE-314) 

- sentry-core/src/performance.rs
- sentry-tower/src/http.rs
- sentry-types/src/protocol/v7.rs
This allows the ability to set a SpanStatus, and does so in the tower http integration.
> feat: Add ability to set a SpanStatus

- sentry-core/src/performance.rs
- sentry-types/src/protocol/v7.rs
The transaction data is called `extra`, and its status is part of the trace context.
> fix: Use correct Transaction props

- sentry/src/transports/curl.rs
- sentry/src/transports/ratelimit.rs
- sentry/src/transports/reqwest.rs
- sentry/src/transports/surf.rs
Rate limiting should prefer the `sentry-rate-limits` header before the
`retry-after` one, and apply a default when no header is present but a
429 response code.
> fix: Apply correct rate limiting behavior/precedence

- sentry-types/src/protocol/v7.rs
This brings the docs in line with how they are documented in relay,
except leaving out the platform specific details.
> docs: Improve DebugImage docs

- sentry-tracing/Cargo.toml
- sentry-tracing/src/converters.rs
- sentry-tracing/src/layer.rs
- sentry/tests/test_tracing.rs
This supercedes #359 and merges it with the latest changes to the tracing integration.
It also adds another test for capturing `&dyn Error` via `tracing::error!()`, which this should all be about.
> feat: Support errors in tracing integration (NATIVE-310)

- Cargo.toml
- Makefile
- sentry-actix/Cargo.toml
- sentry-core/src/performance.rs
- sentry-core/src/scope/noop.rs
We weren't testing this in CI previously. And it would seem that this was broken
in the monorepo anyway, since it requires `resolver = "2"` in order not to unify
features.
supercedes #415, as we still want the API (and trace propagation via headers) to work in such cases.
> fix: Make building without client feature work again

- sentry-tower/src/http.rs
- sentry-tower/src/lib.rs
The TowerService::call seems to just create futures, and is not running in the context of a parent layers future. Also the other way around, `SentryService` didn’t wrap the `call` in a `Hub` either.
> fix: Prevent Memory leaks from sentry-tower

- sentry/Cargo.toml
- sentry/src/transports/curl.rs
Curl doesn't need `serde_json` support since Sentry already serializes envelopes to a vector of bytes internally.  Likewise no other transport sets the `Content-Type: application/json` header, presumably because the data is multiple json objects concatenated together.
> meta: Remove serde_json feature from `curl`

- sentry/Cargo.toml
- sentry/README.md
- sentry/src/lib.rs
- sentry/src/transports/mod.rs
- sentry/src/transports/ureq.rs
Ureq is easy to use, smaller than the other http crates and doesn't pull in as many crate dependencies either, which is why [we] are actively switching to it and in need of an `ureq` transport in Sentry too.
[we]: https://github.com/Traverse-Research
> feat: Add `ureq` transport support

- sentry/Cargo.toml
- sentry/src/transports/curl.rs
- sentry/src/transports/mod.rs
- sentry/src/transports/reqwest.rs
- sentry/src/transports/surf.rs
- sentry/src/transports/thread.rs
- sentry/src/transports/tokio_thread.rs
- sentry/src/transports/ureq.rs
These transport backends don't need the overhead of a tokio runtime and all the dependency crates that come with it, when they are already blocking on their own.  A simple Rust thread and mpsc channel is enough.  The transport thread implementation is duplicated between a tokio and non-tokio module that are used by reqwest/surf, and curl/ureq respectively.
See also https://github.com/getsentry/sentry-rust/pull/419#discussion_r794287640 where this was briefly discussed.
- Refactor this a bit to not duplicate the entire thing.  Perhaps leave both implementations in the same file with some cfgs so that common changes are more easily shared.  In the end the only difference is in the `fn new()` signature and the contents of the thread closure...
- Figure out what to do with `surf`, which [has …
> refactor: Remove tokio dependency for blocking ureq and curl transports

- CHANGELOG.md
The previous `meta` PR(s) for the changelog seemed autogenerated, but given recent commits I thought I should at least add my own items to the list to save you the hassle ;)
> meta: Add #519 (`ureq` transport support) to the changelog

- sentry-types/src/protocol/v7.rs
This adds a GPU Context that matches the API description from [Sentry](https://develop.sentry.dev/sdk/event-payloads/contexts/#gpu-context), with one exception, I've added a `driver_version` field as that particular piece of information is much more important/interesting than some of the other fields that are already present in the format.
> Add GpuContext

- CHANGELOG.md
- sentry-tracing/src/converters.rs
- sentry/tests/test_tracing.rs
This adds the line information that tracing provides back into the
event.  It also moves around the tags into a custom context instead of
the "extra" grab-bag as this is less likely to step on the user's
ad-hoc toes.
Related to #427
> feat(tracing): Add line information from tracing

- sentry-core/src/performance.rs
- sentry-core/src/scope/real.rs
- sentry/tests/test_tracing.rs
A call to `Scope::set_transaction` will now also forward the given name to the currently running performance monitoring transaction to override the `name` it was started with.
> ref: Forward set_transaction to a running Transaction

- .github/workflows/weekly.yml
With the workflow being to create a fork in order to contribute to this project, this fork shouldn't automatically run scheduled linting jobs on the main branch (wherever that happened to be when the fork was cloned/created) and bothering the fork-er with it if it's non-compliant.
Note: I'd love to have this `if` in the `on:` configuration to not even add `Weekly CI` to the GH actions overview (with 2 skipped jobs), but this does not seem possible according to https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions. Suggestions welcome!
> ci/weekly: Only run scheduled jobs on the upstream repository

- sentry-tower/src/http.rs
- sentry-tower/src/lib.rs
See https://github.com/getsentry/symbolicator/pull/687#issuecomment-1048694346 for some context.
> docs: Advise users to override automatic transaction name

- CHANGELOG.md
- sentry-core/src/performance.rs
- sentry-types/src/protocol/v7.rs
- sentry/examples/performance-demo.rs
- sentry/tests/test_tracing.rs
This allows the request information to be sent with the transaction data, which then means `http.method` etc automatically get populated on the Sentry side. Let me know if you want this to be a different way or if I am missing something. Like I was unsure what to do about `Span` and I'm not sure this is correct but I know it works for Transaction
> add request to transaction

- sentry-backtrace/Cargo.toml
This fixes a security vulnerability. https://github.com/rust-lang/regex/commit/ae70b41d4f46641dbc45c7a4f87954aea356283e
> build(backtrace): Update regex to 1.5.5

- .github/workflows/ci.yml
- sentry-anyhow/src/lib.rs
- sentry-tower/src/lib.rs
- sentry-tracing/src/layer.rs
- sentry/src/transports/curl.rs
- sentry/src/transports/reqwest.rs
- sentry/src/transports/ureq.rs
Some intradoc links were broken because their crates are only available as `dev-dependencies`, while others unnecessarily had a forced link to `docs.rs` which could also be an intradoc link (in turn pointing to locally built documentation if not building on docs.rs).
To make sure these links don't break again over time, build-test the documentation in the CI while disallowing any warnings which includes broken links.
> Build-test documentation in the CI and fix/improve broken links

- sentry-tracing/src/converters.rs
- sentry/tests/test_tracing.rs
When using `#[tracing::instrument(err)]` to emit error events when the wrapped function returns an error. Sentry logs show the event as an "unlabled event" 
This PR extracts the error message as a string when the message cannot be found.
> fix: Handle #[instrument(err)] by extracting the error message

- sentry/src/transports/curl.rs
- sentry/src/transports/reqwest.rs
- sentry/src/transports/ureq.rs
- sentry/tests/test_client.rs
Interestingly, the `surf` transport does not support proxy settings at all.
fixes #447 and fixes #448
> fix: Do not panic on invalid Proxy

- sentry-tower/Cargo.toml
- sentry-tower/src/http.rs
`request.uri()` may contains only relative URI (e.g. `/foo/bar`), but `Url::parse` requires full URL with base (e.g. `http://localhost/foo/bar`). So `request.uri().to_string().parse()` can fail.
This PR adds a fixed `http://` scheme if the scheme does not exist and a host from the `host` header if the authority does not exist before parsing the URL.
----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.
> Fix sentry-tower URL generation

- README.md
- README.tpl
- sentry-actix/README.md
- sentry-anyhow/README.md
- sentry-backtrace/README.md
- sentry-contexts/README.md
- sentry-core/README.md
- sentry-debug-images/README.md
- sentry-log/README.md
- sentry-panic/README.md
- sentry-slog/README.md
- sentry-tower/README.md
- sentry-tracing/README.md
- sentry-types/README.md
- sentry/README.md
Update logo to use media queries so it looks good on both dark and light themes.
See https://github.com/getsentry/sentry/pull/34229 for screenshot of effect, or view readme on this branch after [changing your theme](https://github.com/settings/appearance).
> chore: Update logo for dark or light theme

- sentry-tracing/src/layer.rs
this fixes #440 
spans later in the functions were working and showing up in the UI but not the original set of values passed to the function.
> add initial values for functions to the data

- sentry-core/src/scope/real.rs
Noticed these were missing after #466
> fix: Add items missing from Scope debug impl

- sentry-backtrace/Cargo.toml
- sentry-backtrace/src/parse.rs
- sentry-backtrace/src/trim.rs
- sentry-backtrace/src/utils.rs
- sentry-core/Cargo.toml
- sentry-core/src/clientoptions.rs
- sentry-core/src/constants.rs
- sentry-core/src/hub.rs
- sentry-core/src/test.rs
- sentry-debug-images/Cargo.toml
- sentry-debug-images/src/integration.rs
Piggybacking on the [motivation in winit]: `lazy_static!` is a macro whereas `once_cell` achieves the same using generics.  Its implementation has also been [proposed for inclusion in `std`], making it easier to switch to a standardized version if/when that happens.  The author of that winit PR is making this change to many more crates, slowly turning the scales in favour of `once_cell` in most dependency trees.  Furthermore `lazy_static` hasn't published any updates for 3 years.
See also [the `once_cell` F.A.Q.].
In addition "constant" `Vec`tor allocations don't need to be wrapped in a `lazy_static!` macro call at all but can be replaced with true `const` slices (or `const` sized arrays, but those are slightly more tedious to construct).
[motivation in winit]: …
> Replace ancient `lazy_static` crate with `once_cell` or `const` slices

- CHANGELOG.md
- sentry-actix/Cargo.toml
- sentry-anyhow/Cargo.toml
- sentry-backtrace/Cargo.toml
- sentry-contexts/Cargo.toml
- sentry-core/Cargo.toml
- sentry-debug-images/Cargo.toml
- sentry-log/Cargo.toml
- sentry-panic/Cargo.toml
- sentry-slog/Cargo.toml
- sentry-tower/Cargo.toml
- sentry-tracing/Cargo.toml
- sentry-types/Cargo.toml
- sentry/Cargo.toml
> Two other interesting things we could do after this MSRV bump:
> Add the rust-version field to the manifest, which was added in 56: https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
> As well as update to edition 2021, which was also added in 56 🎉
https://github.com/getsentry/sentry-rust/pull/472#pullrequestreview-1010385880
> ci: Add rust-version and update edition to 2021

- CHANGELOG.md
- sentry-types/src/protocol/attachment.rs
- sentry-types/src/protocol/envelope.rs
The implementation is highly inspired by https://github.com/getsentry/relay/blob/master/relay-server/src/envelope.rs and it includes most its deserialization tests.
We do not handle unknown item types for now, as it would require significant changes in how serializing works and how we store the envelopes. Thus we decided to skip it, for now, to support only item types that `sentry-rust` implements and enhance this feature in the future.
This will be enough to unblock https://github.com/getsentry/sentry-cli/issues/703 anywya.
Closes https://github.com/getsentry/sentry-rust/issues/381
> feat: Implement Envelope::from_path and Envelope::from_slice

- CHANGELOG.md
- sentry-core/Cargo.toml
- sentry-core/src/client.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/lib.rs
- sentry-core/src/performance.rs
- sentry-core/src/profiling.rs
- sentry-types/src/protocol/envelope.rs
- sentry-types/src/protocol/mod.rs
- sentry-types/src/protocol/profile.rs
- sentry-types/src/protocol/v7.rs
- sentry/Cargo.toml
- sentry/src/transports/ratelimit.rs
This PR adds support for the profiling feature.
For this first iteration we will stick to the design implementation of the mobile profilers (`Android`/`iOS`) with one profile being linked to one transaction.
* adds `enable_profiling` option to enable/disable profiling
* adds `profiles_sample_rate` option to further sample profiles with respect to the transactions. This is dependent on `traces_sample_rate` and the probability of a profile being collected is: `traces_sample_rate * profiles_sample_rate` 
* only one profile at a time can be collected. If the profiler is running, no other profiles will be collected when other transactions start
> feat(profiling): Add support for Profiling

- sentry-core/Cargo.toml
- sentry-core/src/profiling.rs
This solves a problem (probably due to unwind) on macos, where the profiler would
yield a `Trace/BPT trap`.
Instead of using the `backtrace` crate, when running on `macos`, using `frame-pointer`
is more recommended to get the backtrace.
> fix(profiling): Add support to use frame-pointer on macos

- sentry-core/src/performance.rs
This check is already happening in Relay.
The idea is drop it already on the client side in order to avoid waste of resources on Relay.
> feat(profiling): Drop the profile when no sample were collected

- sentry-core/Cargo.toml
One of the pprof default features (`cpp`) pulls in `symbolic-demangle`,
which is used for demangling, but we don't use that feature at all since
we are only interested in raw instruction addrs which we symbolicate and
demangle server-side.
> fix: Turn of pprof default features

- sentry-contexts/src/utils.rs
- sentry-core/src/clientoptions.rs
- sentry-log/src/logger.rs
- sentry-slog/src/drain.rs
- sentry-types/src/protocol/mod.rs
- sentry/Cargo.toml
The new feature activates the sentry-tower/http feature, as otherwise one would have to
declare sentry-tower separately which can lead to out-of-sync dependency versions.
This also fixes all the new clippy lints as a drive-by change, those should be rather minimal.
> ref: Add a tower-http feature as a shortcut

- scripts/bump-version.sh
- scripts/generate-readme.sh
- scripts/update-readme.sh
Mostly just double quotes  for variables to satisfy the shellchek. 
And also remove `echo` and `sed` from [`scripts/generate-readme.sh`](https://github.com/getsentry/sentry-rust/compare/fix/small-improvements-for-shell-scripts?expand=1#diff-a85909ed3be999ca8de0cc440657a41460a29d6054f16a255b612fa53c479254)  - and use only bash substitution syntax.
> ref: Add small improvements to bash scripts

- sentry-contexts/Cargo.toml
- sentry-contexts/src/utils.rs
Add Windows OS version to the `Context::Os` context. A test was also added to verify that the version string we're getting back is non-empty and not equal to the `Version::Unknown` version from the `os_info` crate.
On my windows machine, this will give a version string of `10.0.19044`. Previously, all windows crashes reported had the version reported as `Unknown`.
Fixes #500
> feat(contexts): Add Windows OS version to OS context

- sentry-core/Cargo.toml
- sentry-core/src/hub.rs
- sentry-core/src/lib.rs
- sentry-types/src/protocol/envelope.rs
- sentry/src/lib.rs
This explains the parallelism and concurrency story around Hubs with added examples of parallel multithreading and concurrent futures usage.
> ref: Improve Hub concurrency docs

- sentry-contexts/src/utils.rs
- sentry-core/Cargo.toml
- sentry-core/src/macros.rs
- sentry-tower/Cargo.toml
- sentry-tower/src/http.rs
- sentry-tower/src/lib.rs
- sentry/Cargo.toml
- sentry/examples/anyhow-demo.rs
- sentry/examples/log-demo.rs
- sentry/examples/thread-demo.rs
- sentry/examples/tracing-demo.rs
- sentry/src/transports/curl.rs
- sentry/src/transports/mod.rs
- sentry/src/transports/reqwest.rs
- sentry/src/transports/surf.rs
- sentry/src/transports/ureq.rs
- sentry/tests/test_basic.rs
- sentry/tests/test_log.rs
- sentry/tests/test_tower.rs
- sentry/tests/test_tracing.rs
Previously it was impossible to have a unified feature named `rustls` or `native-tls` that would turn on the respective TLS backend in the chosen transport (`reqwest` or `ureq`) as a feature of `<crate>/tls` would implicitly turn on `<crate>`.  Since Rust 1.60 it is now possible to specify this crate-feature enablement through the use of the question mark in `<crate>?/tls`, which will only enable the `tls` feature if `<crate>` was enabled through other means (another feature).
Secondly we can now also let optional crates have the same name as a feature, and use `dep:<crate>` to refer to the crate instead of the dependency, making for a more pleasant experience without renames to underscore suffixes.
---
Filing this as draft just to get the word out and discuss this for a bit, as it will …
> Take advantage of weak features in Rust 1.60 for TLS enablement

- CHANGELOG.md
- sentry-contexts/src/utils.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/hub.rs
- sentry-core/src/performance.rs
- sentry-core/src/profiling.rs
- sentry-panic/src/lib.rs
- sentry-types/src/protocol/envelope.rs
- sentry-types/src/protocol/v7.rs
- sentry/src/transports/curl.rs
- sentry/src/transports/reqwest.rs
- sentry/src/transports/surf.rs
- sentry/src/transports/ureq.rs
- sentry/tests/test_tracing.rs
This PR adds the `traces_sampler` option to `ClientOptions`, and respects it when making transaction sampling decisions as detailed in the SDK guidelines: https://develop.sentry.dev/sdk/performance/#sdk-configuration
There was some prior work on this topic in https://github.com/getsentry/sentry-rust/pull/288, however by now it's pretty stale so I started fresh.
Points for review:
- To implement `Debug` for this option I just print the function's memory address (if set); I can't think of something simple that would have more value to the user. [link](https://doc.rust-lang.org/std/ptr/macro.addr_of.html)
- If accepted, I would like to update the official docs with the new option, could someone point me in the right direction for that?
- Adding a new field to `ClientOptions` is a breaking …
> sentry-core: add traces_sampler client option

- CHANGELOG.md
- sentry-core/src/performance.rs
- sentry/tests/test_client.rs
Split from #512, to enable support for `traces_sampler` inspecting first class properties of `TransactionContext`.
This was split as we though the addition of `CustomTransactionContext` may require further discussion, while these changes should be uncontroversial.
ref: https://github.com/getsentry/sentry-rust/pull/512#issuecomment-1304747662
> sentry-core: add public getters for TransactionContext

- sentry-core/Cargo.toml
This new version of `pprof-rs` introduces some important fixes among which one that let us run profiling on unix without frame-pointers (using libunwind) seamlessly.
> sentry-core: update pprof dependency to version 0.11.0

- sentry-core/src/hub.rs
- sentry-core/src/hub_impl.rs
- sentry-core/src/lib.rs
Avoids a lot of annoying `#[cfg]` wrapping and should make it easier to add things.
> ref: Move HubImpl to its own file

- sentry-core/Cargo.toml
- sentry-core/src/futures.rs
- sentry-core/src/hub_impl.rs
Use a `SwitchGuard` internally as a replacement for `Hub::run` which does
not require passing a closure, and does not go through `panic::catch_unwind`,
as `Drop` impls are guaranteed to be executed even when panics are unwinding.
fixes #522
> ref: Switch Hubs using a Guard

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/weekly.yml
- Update actions versions.
- Switch to cargo-llvm-cov.
> ref: Update CI Workflows

- CHANGELOG.md
- sentry-core/Cargo.toml
- sentry-core/src/hub_impl.rs
Turns out ArcSwap does have a slight cost. The previous implementation used `UnsafeCell`, so switch back to that.
> ref: Switch back to UnsafeCell from ArcSwap

- sentry/README.md
Seems like the `native-tls`/`rustls` features now use the new cargo syntax, so the separate feature flag `ureq-native-tls` was removed. This PR aligns the crate readme with that change.
> docs: fix outdated `native-tls`/`rustls` info in README

- sentry-core/src/performance.rs
I would like to add the Sentry trace_id to our internal logs to be able to correlate it with the sentry transaction. Currently this isn't publicly accessible anywhere.
> sentry-core: make TransactionContext.trace_id readable

- sentry-core/src/performance.rs
Raised in review of https://github.com/getsentry/sentry-rust/pull/533#issuecomment-1375551161
This PR exposes the `TraceContext` stored on a `Transaction` or `Span`.
All data on the `TraceContext` is publicly readable in other SDKs, such as Python or Javascript.
- Rust struct: https://github.com/getsentry/sentry-rust/blob/5013eb1fdca505ef9c7c28266afcf847da7c17b3/sentry-types/src/protocol/v7.rs#L1439
- Python analagous class: https://github.com/getsentry/sentry-python/blob/d0eed0ee828684f22fe2a2b28b02cf7f4ce8c74a/sentry_sdk/tracing.py#L81
> sentry-core: make TraceContext publicly readable

- .github/workflows/weekly.yml
I disabled scheduled jobs on forks in #435 to prevent [unnecessary spam from steps that are not supposed to succeed anyway], but @Swatinem removed the check in #528 for an undocumented reason.  Add it back to not bother forkers with day-to-day issues, while still allowing them to test/see CI results locally on push (to one of a limited set of preconfigured branches).
[unnecessary spam from steps that are not supposed to succeed anyway]: https://github.com/MarijnS95/sentry-rust/actions/runs/3926205216
> Re-disable scheduled jobs on forks

- sentry-core/src/performance.rs
- sentry-core/src/profiling.rs
- sentry-types/src/protocol/v7.rs
As per [RFC 0047](https://github.com/getsentry/rfcs/blob/main/text/0047-introduce-profile-context.md)
> feat(profiling): Add profile context to transaction.

- sentry-actix/src/lib.rs
Actix `request.match_name()` is buggy. 
It doesn't care about the HTTP verb. It only looks at the `path`. Thus 2 routes with the same `path` will have the same match name. 
Previously, `format!("{} {}", req.method(), req.uri())` was already used as a fallback for the transaction name.
These changes make it as the default transaction name.
> fix actix match name bug

- CHANGELOG.md
- sentry/src/transports/tokio_thread.rs
Fixes #543.
I am unsure if there is anything better than `eprintln` we can do in the error case—would using e.g. the `sentry_debug` macro exacerbate the problem because it also tries to send on the same channel?
> fix: Don't block on sending envelopes

- sentry-types/src/protocol/envelope.rs
This turns the type of `Envelope::items` into an enum that may be a vector of `EnvelopeItems` (the status quo) or a blob of binary data. In the latter case, operations on items become no-ops because nothing can be done if there's no structure to the items.
It also adds a function `from_path_raw` that reads an Envelope from disk without attempting to parse any items. The motivation for this is https://github.com/getsentry/sentry-cli/issues/1458.
> feat: Allow Envelopes to contain raw binary data

- CHANGELOG.md
- sentry-core/src/performance.rs
This adds a `data` method to `performance::Span` that gives exclusive access to the underlying `protocol::Span`'s `data` field (a map from `String` to `protocol::Value`). Since the inner span is behind a `Mutex`, the `data` method returns a `Data` smart pointer that holds the lock.
> feat(tracing): Add method for accessing span data

- sentry-backtrace/Cargo.toml
regex as used by Sentry doesn't need full Unicode tables, just ones used by `\w`, `\s`, `\d` and `\b` (`unicode-perl` feature). This reduces size of the binary.
> build(backtrace): Disable most of default regex features

- sentry-core/src/profiling.rs
- sentry-types/src/protocol/profile.rs
Removes deprecated fields `relative_start_ns` and `relative_end_ns` from TransactionMetadata and replace Vec<TransactionMetadata> with a single TransactionMetadata.
This is meant to align the SDK with PR [#1878](https://github.com/getsentry/relay/pull/1878)
> ref(profiling): remove deprecated fields from profile data

- sentry-core/src/clientoptions.rs
- sentry-core/src/performance.rs
- sentry-core/src/profiling.rs
Similarly to `TracesSampler`, this PR aims to add support for a `ProfilesSampler`.
> feat(profiling): add ProfilesSampler

- sentry-core/src/profiling.rs
This is intended to align (as far as the profile timestamp is concerned) the SDK with the official `sample format` [doc](https://develop.sentry.dev/sdk/sample-format/) recently uploaded.
```
timestamp
String, recommended. The timestamp when the profile was captured by 
the SDK as [RFC 3339] format. This is meant to be the anchor for all 
relative timestamps captured for the profile.
Ideally, this will be the same as the field start_timestamp on the transaction so all 
relative timestamps for transaction and profile can be both from the same reference 
point and we don't need to correct relative timestamps.
If for some reasons, the profiler implementation doesn't allow that, set it to the closest 
time to the profiler start (or to whatever the profiler gives you as a profile start …
```
> ref(profiling): make profile timestamp the same as transaction start_timestamp

- sentry/src/transports/ureq.rs
> Add default TlsConnector for ureq when native-tls is enabled

- sentry-panic/README.md
Sentry wasn't working for me because I was calling `std::panic::set_hook()` after `sentry::init()`.   Make it clear that you can have your own hook too, as long as you set it first.
> Add chaining documentation

- sentry-types/src/protocol/envelope.rs
We used to print an empty `{}` header in front of raw envelopes, which is wrong.
Now we test for perfect roundtrips of arbitrary bytes, which is what "raw" means. Also offers a `from_bytes_raw` now which takes an in-memory buffer.
> Fix raw envelope roundtrips

- sentry-tower/Cargo.toml
- sentry-tower/src/http.rs
If the `axum-matched-path` feature of `sentry-tower` is used, it will enable the corresponding `matched-path` feature of `axum` and use the `MatchedPath` request extension to generate the transaction name. As before, the HTTP method is also still included in the transaction name.
Resolves https://github.com/getsentry/sentry-rust/issues/541
/cc @Swatinem
> sentry-tower: Use `axum::MatchedPath` for transaction names

- sentry-tower/src/http.rs
Without this the transaction does not have any HTTP request metadata attached, because apparently the event processor is not running for performance traces. After this patch the performance trace looks like this:
Note that I had to reorder the contents of the `configure_scope()` callback to be able to access `sentry_req` before it disappears into the `add_event_processor()` callback.
This should address https://github.com/getsentry/sentry-rust/pull/439#pullrequestreview-903980053
/cc @Swatinem
> tower: Use `tx.set_request()` to set HTTP request metadata

- sentry-core/src/performance.rs
- sentry-core/src/profiling.rs
Better to leave Relay set it.
This will ensure the profile is correctly accepted and validated before we set it instead of having to remove the profile id from the context in case the profile is rate limited/invalid or else.
> ref(profiling): do not set the profile_id in the profile context on the transaction.

- sentry-types/src/protocol/envelope.rs
- sentry-types/src/protocol/mod.rs
- sentry-types/src/protocol/monitor.rs
- sentry-types/src/protocol/v7.rs
Adds types that define monitor check-in envelopes.
This is essentially a copy from https://github.com/getsentry/relay/blob/master/relay-monitors/src/lib.rs#L39-L142
We would like to use this in sentry-cli to generate monitor check-ins
> feat(crons): Add monitor check-in types to sentry-types

- sentry-backtrace/src/trim.rs
- sentry-tracing/Cargo.toml
- sentry-tracing/src/converters.rs
- sentry/Cargo.toml
- sentry/tests/test_tracing.rs
Changes how the tracing integration tracks errors with messages and provides more structured data for fields passed via tracing. 
First, this introduces the ability to set Sentry tags via a `tags.*` prefix. The prefix is removed and does no longer occur in the tracing context. The following example will create a tag called `foo`:
```rust
tracing::error!(tags.foo = "bar", "this is an error");
```
Next, the custom context is renamed to `Rust Tracing Fields`. This is closer to the original naming in the `tracing` crate and also disambiguates this data more from Sentry tags.
The top-level exception passed to tracing is now marked with a `tracing` mechanism to annotate in the UI how the exception was captured.
Finally, if both a message and an error are passed to tracing, the message gets …
> feat(tracing): Improve structure for tracing errors

- sentry-tracing/Cargo.toml
- sentry-tracing/src/lib.rs
> doc(tracing): Add docs for errors and custom tags with tracing

- sentry-types/src/protocol/v7.rs
- sentry-types/tests/test_protocol_v7.rs
~Currently, tests are failing due to visitor going more than one level deep and nested objects effectively getting top-level key assigned to them.~
~Or rather, after more investigation, it simply puts a `type` field into the flattened `other` map, as `type` is not removed; it normally is, as it's used as `tag = "type"` during deserialization.~
tl;dr - we want both variants to be deserializable (currently first example is failing due to missing `type` key):
``` json
{
"contexts": {
"device": {
"name": "fancy name for a fancy server",
"arch": "amd64",
"num_cpu": 8
},
}
```
```json
{
"contexts": {
"device": {
"type": "device",
"name": "fancy name for a fancy server",
"arch": "amd64",
"num_cpu": 8
},
}
```
Closes https://github.com/getsentry/sentry-rust/issues/483
> fix: Allow for Contexts data type to be infered from the key value

- sentry-core/src/scope/real.rs
- sentry-types/src/protocol/v7.rs
Follow-up to https://github.com/getsentry/sentry-rust/pull/590
Fixes https://github.com/getsentry/sentry-rust/issues/575
Per https://develop.sentry.dev/sdk/event-payloads/transaction/
> Transactions are [Events](https://develop.sentry.dev/sdk/event-payloads/) enriched with [Span](https://develop.sentry.dev/sdk/event-payloads/span/) data.
> ref: Apply user field from scope to transaction event

- sentry-tower/Cargo.toml
- sentry-tracing/Cargo.toml
I found e.g. `SentryHttpLayer` missing from docs.rs for `sentry-tower` so I went ahead and added the necessary `docs.rs` metadata to `Cargo.toml` for `sentry-tower` and `sentry-tracing` (those were the packages with non-default features that didn't have it enabled yet).
> Enable building sentry-tower and sentry-tracing with all features on docs.rs

- sentry-core/src/scope/real.rs
Instead of having the compiler do bounds-checks and generate panic-ing code, just make that case impossible by making sure there is always a top scope.
> Micro-optimize Scope access

- Cargo.lock
- sentry-core/src/api.rs
- sentry-core/src/client.rs
- sentry-core/src/performance.rs
- sentry-core/src/session.rs
- sentry-types/Cargo.toml
- sentry-types/src/lib.rs
- sentry-types/src/protocol/session.rs
- sentry-types/src/protocol/v7.rs
The `getrandom` crate uses syscalls to get *true* randomness from the OS. We do not need that high quality of randomness, we do not even need cryptographically secure randomness.
This switches to the `rand` crate which uses a reseeding PRNG which is still cryptographically secure though.
This is much faster, and we can switch to an even simpler PRNG if it is not fast enough still.
> Use `rand` instead of `getrandom` for IDs

- sentry-tower/src/lib.rs
It is common to have this integration pulled in via the tower feature of the sentry crate.  In this case it is convenient to know about the shortcut of the tower-http feature instead of having to add a direct dependency to sentry-tower.
> docs(tower): Mention how to enable http feature from sentry crate

- Cargo.lock
- sentry-types/Cargo.toml
- sentry-types/src/crontab_validator.rs
- sentry-types/src/lib.rs
- sentry-types/src/protocol/monitor.rs
I will want to use the new `MonitorSchedule::from_crontab` in getsentry/sentry-cli#1807
> MonitorSchedule constructor that validates crontab syntax

- Cargo.lock
- sentry-tower/Cargo.toml
Hi,
I'm not sure if you accept contributions so feel free to close this if not. 
Axum recently update to `0.7.0` which doesn't compile using sentry `0.31.8`, as it turns out this is simple to fix by bumping the http dependency in `sentry-tower` to `1.0.0` to match that in axum.
> Support for axum 0.7.1

- CHANGELOG.md
- Cargo.lock
- sentry-core/Cargo.toml
- sentry-log/Cargo.toml
- sentry-tower/Cargo.toml
- sentry/Cargo.toml
This does a `cargo update` and manually bumping a ton of other dependent crates.
`tonic` still pulls in an older `axum` version, so a ton of dependencies are still duplicated.
> Update crate dependencies

- sentry-core/src/performance.rs
- sentry-tracing/src/converters.rs
- sentry-tracing/src/layer.rs
Implementing https://github.com/getsentry/sentry-rust/issues/617
Adds a `enable_span_attributes()` method for the `sentry_tracing::SentryLayer` that activates the desired behaviour.
The root span's attributes can only be propagated once the traces enabled (e.g. through `ClientOptions::traces_sample_rate`).
> tracing: send spans' attributes along with the event ones

- CHANGELOG.md
- Cargo.lock
- sentry-core/Cargo.toml
- sentry-core/src/cadence.rs
- sentry-core/src/client.rs
- sentry-core/src/hub.rs
- sentry-core/src/lib.rs
- sentry-core/src/metrics.rs
- sentry-core/src/units.rs
- sentry-types/Cargo.toml
- sentry-types/src/protocol/envelope.rs
- sentry/Cargo.toml
- sentry/src/transports/ratelimit.rs
This adds:
- A new `statsd` EnvelopeItem
- A new `MetricAggregator` which is implemented similarly to the Python prototype implementation 
- The Client instantiates a metric flusher and starts it in the background
- A `Metric` type that allows building and sending metrics, which is the primary user-facing API
- A `cadence`-compatible `SentryMetricSink` that makes it easier to integrate Sentry into existing environments
- Internal types that are mostly adapted from `relay-metrics`
This PR does not yet include support for code locations and span linking; both will follow at a later stage.
> Add experimental metrics implementation

- sentry-core/src/hub.rs
In a very specific combination of events, any event emission can deadlock if it tries to add stuff to the Hub, like breadcrumbs. This can be easily reproduced with the following setup:
- `sentry-log` (or `sentry-tracing` if `tracing-log` is set up)
- event filtering configured to generate breadcrumbs for debug logs
- any cause for events to not be sent to the server
Should the event fail to be sent for too long, the channel to the sender thread fills up and events start to be dropped. This will generate a debug log line, logging that an event has been dropped and why. With `sentry-log` (or `tracing-log` + `sentry-tracing`), this would generate a breadcrumb.
However, the whole call to `Transport::send_envelope` is done in the context of `HubImpl::with`, that holds a read lock on the …
> fix(hub): avoid deadlocks when emitting events

- sentry-types/src/protocol/envelope.rs
- sentry-types/src/protocol/monitor.rs
Need these fields to implement https://github.com/getsentry/sentry-cli/issues/1919
> feat(crons): Add new fields to `MonitorConfig` type

- sentry-core/src/metrics.rs
Gauges are serialized as `last:min:max:sum:count`. When parsing a gauge as a `Metric`, we only want the last value, so we need to take care to discard everything after the first `:`.
See #639.
> fix(metrics): Parse serialized gauge values

- sentry-core/src/client.rs
The `Standard` distribution in `rand` produces a half-open range for floating points: https://docs.rs/rand/latest/rand/distributions/struct.Standard.html#floating-point-implementation. This means there is a 1-in-a-billion chance that a random number will be <= a sample rate of 0.0, even though 0.0 should disable the transactions feature.
I've actually seen this happen exactly once haha
> fix 1-in-a-billion chance to sample with 0.0 sample rate

- Cargo.lock
https://rustsec.org/advisories/RUSTSEC-2024-0332.html
H2 client is [not affected](https://seanmonstar.com/blog/hyper-http2-continuation-flood/) but this update will make things like cargo audit happy.
> Update h2 crate because of RUSTSEC-2024-0332

- sentry/Cargo.toml
- sentry/src/transports/embedded_svc_http.rs
- sentry/src/transports/mod.rs
This small pr adds support for sending envelopes using the embedded-svc http transport available on the esp32 microcontroler.
With this in place it is possible to use sentry in rust (with std) based esp32 projects.
> Add embedded-svc based http transport

- Cargo.lock
- sentry-core/Cargo.toml
The latest release includes `regex` and family—I'd very much like to avoid those if possible, since they are big chunky crates with slow compile times.
For now, the easiest thing seems to be to gate the inclusion of `regex` on `UNSTABLE_metrics` since it is only used in that code path.
Longer-term, I'd appreciate either reverting to the pre- #658 implementation that looks something like `c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.' | '/')` (since it's a relatively simple regex) or looking into a lighter crate like [regex-lite](https://crates.io/crates/regex-lite).
> Make regex an optional dependency

- CHANGELOG.md
- Cargo.lock
- sentry-core/Cargo.toml
- sentry-core/src/cadence.rs
- sentry-core/src/client.rs
- sentry-core/src/lib.rs
- sentry-core/src/metrics/normalization/normalized_tags.rs
- sentry-types/Cargo.toml
- sentry-types/src/protocol/envelope.rs
- sentry/Cargo.toml
- sentry/src/transports/ratelimit.rs
- sentry/src/transports/ureq.rs
Removes the `UNSTABLE_` prefix from the feature flag. Also runs a `cargo update` and updates some dependencies for good measure.
> Stabilize the `metrics` feature

- sentry-core/src/client.rs
Hopefully this will improve const propagation and avoid making calls to rng (which may be slow) when sampling is entirely disabled anyway.
> Don't generate a random to choose whether we should sample if sampling is fully disabled (rate = 0.0)

- sentry-types/src/protocol/v7.rs
These are required to construct some public types, so the good practice is to reexport them so that users can use them without specifying the dependency explicitly themselves and be less likely to break on update.
> Reexport Url and Uuid in `protocol`

- sentry-core/src/lib.rs
I needed the type during sentry init for conditional callback depending on context, and ended up having to duplicate this type to pass it around. Figured it would be much better to actually import it but it is currently not possible.
Cheers
> chore: export `BeforeCallback` type

- sentry/src/transports/thread.rs
- sentry/src/transports/tokio_thread.rs
The PR for the [issue](https://github.com/getsentry/sentry-rust/issues/677).
> Fix `Transport::flush` implementation for `TransportThread`

- sentry-core/src/performance.rs
- sentry-types/src/protocol/v7.rs
Currently transactions do not include a `server_name` which makes it harder to know where a transaction occurred. 
According to the [transaction docs](https://develop.sentry.dev/sdk/event-payloads/transaction/):
>Transactions are Events enriched with Span data
And the [events docs](https://develop.sentry.dev/sdk/event-payloads/) include `server_name` so I don't see any reason not to include it. 
Perhaps in the future it might make more sense to have a common struct between the two that gets flattened (through serde) such that when `Event` gets new fields that may be useful in a `Transaction` then it'll already be there (as long as the function to enrich that hypothetical shared struct is used in both places). This, however, is outside of the scope of what I need at this time so I only did …
> add server_name to transaction data

- sentry-core/src/performance.rs
currently the only tags added to transactions are the tags on the scope at the time you finish a transaction. Sometimes, however, it is useful to have tags that aren't for the scope but just for the transaction. 
I am using the same signature as the equivalent method in `Scope`. 
I know there are currently other PRs related to tags in transactions but I think those are more specific to the tracing integration so having methods  to do it explicitly in a transaction (or span) is still useful.
> Allow settings tags directly on transactions/spans

- CHANGELOG.md
- sentry/src/transports/thread.rs
This is a followup to #546 (for #543):
Any transport is susceptible to #543, where sending too many events to Sentry can block. So the `thread::TransportThread` impl should similarly drop events instead of blocking, just as the similar `tokio_thread::TransportThread` began doing with the fix in #546.
> fix: Don't block on sending envelopes (ureq/curl transports)

- sentry-panic/src/lib.rs
Fixes the clippy failure on `master`. I decided to allow the deprecated use to avoid bumping MSRV to 1.81.
> fix: allow deprecate `PanicInfo`

- Cargo.lock
- sentry/Cargo.toml
As of rustls 0.23, `aws-lc-rc` is the default crypto backend of rustls. In order to allow binaries to choose, which crypto backend to use, libraries need to disable rustls' default features.
> fix: disable rustls features by default

- sentry-tracing/tests/tracing.rs
This is follow up to my PR https://github.com/getsentry/sentry-rust/pull/696
Adds basic test to verify that tracing layer correctly adds tags to the transaction
> Add basic test for tracing layer

- sentry-core/src/hub.rs
- sentry-core/src/hub_impl.rs
- sentry-core/src/lib.rs
- sentry-core/src/performance.rs
- sentry-tracing/src/layer.rs
I've been facing a bug with Sentry Trace where concurrent spans end up wrongly nested. At first, I thought this was some strange autogrouping bug and event sent a feedback (sorry Sentry support member 😅).
After digging a little bit, I discovered that the current tracing layer implementation sets the sentry span as active as soon as a tracing span is _created_, which should not be the case, as spans are only active once _entered_. Following the same logic, it also reverts to the parent span only when a span is _closed_, and not when it's exited.
A span can be entered and exited multiple times, for example, when a tracing `Instrumented` future polls and returns Pending. In case of concurrent Instrumented futures, the current impl ends up nesting Futures under the first created one.
> I'd …
> fix(sentry-tracing): switch sentry spans on enter and exit

- sentry-core/src/performance.rs
This change does three things:
1. Add a function to allow creating a `TransactionContext` with a custom Trace ID without a parent span ID.
My company is testing traces on Sentry in parallel to our current trace solution, for ease of use, we'd like to keep using the same trace ID on both platforms for now. Currently, my approach is to create a `sentry-trace` header with a zeroed span ID, but the UI has this bright red alert telling me that the parent span ID is invalid, and this is bugging me. I doubt I'm the only one who has faced this issue before.
2. Implements support for the `traceparent` as stated in getsentry/team-sdks#41. `sentry-trace` still takes precedence. It does **not** emit the header, though. Should it? It only allows for parsing for now.
3. Creates a builder allowing to …
> feat(sentry-core): add support for w3c traceparent

- sentry-core/src/performance.rs
- sentry-tracing/tests/breadcrumbs.rs
- sentry-tracing/tests/shared.rs
- sentry-tracing/tests/smoke.rs
This PR is an attempt to completely resolve #617.
Currently, fields from spans are only recorded when the span gets sampled. This currently happens very early, right when the `Transaction` gets created. As a result, any event that gets recorded afterwards (i.e. as a breadcrumb) does not have access to the current span fields.
By delaying the discarding of `Transaction` to `finish`, we get to retain all the contextual data and still honor the configured sampling.
I ran a performance test of our software with this local branch applied and could not measure any impact of this.
> fix: delay sampling of tracing spans to `finish`

- sentry-core/src/intodsn.rs
- sentry-core/src/performance.rs
- sentry-slog/src/converters.rs
- sentry-types/src/protocol/v7.rs
- sentry-types/src/utils.rs
CI is currently failing due to a new clippy lint.
> chore: elide lifetimes where possible

- sentry-core/src/scope/real.rs
In our application, not all information of the current user is known immediately upfront. The user ID is loaded directly on startup but the account that they log in to is only known later.
Currently, we have to separately track this information because we always have to set the entire user at once. To avoid this, this PR adds a `user` getter to get the current user from the scope. This solves our use-case because we can get the current user and produce a new one that has additional fields and set it again.
Resolves: #706.
> feat: allow retrieving the current user of a scope

- Cargo.lock
- sentry-tower/Cargo.toml
see https://tokio.rs/blog/2025-01-01-announcing-axum-0-8-0
> sentry-tower: Update `axum` dependency to v0.8

- sentry-tower/src/lib.rs
> Make sentry-tower SentryLayer and SentryService `Sync` if request isn't

- sentry-tower/src/http.rs
If the future gets dropped (panic or other reasons), the transaction is never finished.
This change makes sure the future always finishes the transaction and restores the previous context.
> fix(http): Finish transaction on drop

- sentry-actix/src/lib.rs
Without this the transaction does not have any HTTP request metadata attached, because apparently the event processor is not running for performance traces
it just follows the changes done for tower from https://github.com/getsentry/sentry-rust/pull/571
> actix: Use tx.set_request() to set HTTP request metadata

- sentry-core/src/performance.rs
- sentry-tracing/tests/smoke.rs
- sentry-types/src/protocol/v7.rs
The Rust SDK currently sets data on `transaction.extra` when calling `transaction.set_data` on a `Transaction`.
This change makes it so that data is instead set on the `TraceContext` i.e. `transaction.context.trace.data` as other SDKs do (see https://github.com/getsentry/team-sdks/issues/95). 
Required for https://github.com/getsentry/sentry-rust/issues/733
> feat(core): transaction.set_data sets data on TraceContext

- sentry-tracing/src/converters.rs
With this change, we wrap an `Error` captured with e.g. `tracing::error` with the synthetic mechanism for `tracing` only if we effectively have a stack trace to be reported in the error, i.e. feature `backtrace` is enabled and `attach_stacktrace` is enabled.
Without this change, using `tracing::error!(error = <err>, <message>)` without the `backtrace` feature enabled would result in Sentry issues with `<unknown>` as title, as shown in https://github.com/getsentry/sentry-rust/issues/723#issuecomment-2642497057.
Closes #723 
```rust
fn a() {
let err = "NaN".parse::<u32>().unwrap_err();
tracing::error!(error = std_dyn_err(&err), "error with error");
}
fn b() {
let err = File::open("non_existent_file.txt").unwrap_err();
tracing::error!(error = std_dyn_err(&err), "error with error");
}
fn c() …
```
> fix(tracing): wrap error with synthetic mechanism only if attaching stacktrace

- sentry-backtrace/src/process.rs
- sentry-backtrace/src/trim.rs
- sentry-backtrace/src/utils.rs
> ref(backtrace): add entries and extra logic for in-app detection

- sentry-actix/src/lib.rs
Extensions are a feature of Actix-web to pass request-local data.
With this change, we pass the Hub that we create with each Actix request in the extensions, so that other middleware can access it and use it to capture events within the correct hub.
Closes https://github.com/getsentry/sentry-rust/issues/624
> fix(actix): process request in other middleware using correct Hub

- sentry-anyhow/src/lib.rs
This is similar to https://github.com/getsentry/sentry-rust/pull/755 but for the anyhow integration
Without this change, if we're running without `RUST_BACKTRACE` set, then `backtrace` will have value `"<disabled>"`.
We would try to parse it and get an empty vec as a result.
The consequence is that all anyhows would be grouped in a single issue due to having the same (empty) stack trace.
After the change, there will be no stack trace, so grouping will happen according to the error message.
Side effect: when running with `attach_stacktrace: true`, `sentry-backtrace` will kick in and provide a backtrace (this didn't happen before because we had a stack trace, even though it was an empty one).
It could be argued whether we want this or not.
Closes …
> fix(anyhow): attach stacktrace only if anyhow error has backtrace

- Cargo.lock
- sentry-core/Cargo.toml
- sentry-tower/Cargo.toml
- sentry-types/Cargo.toml
- sentry/Cargo.toml
Mostly minor version bumps except for `thiserror` which has been upgraded from `1.0.15` to `2.0.12`.
Most importantly, committing an updated lockfile after dropping `surf` in https://github.com/getsentry/sentry-rust/pull/766 to get rid of outdated subdependencies.
> chore(deps): bump some dependencies and update `Cargo.lock`

- sentry-actix/src/lib.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/lib.rs
- sentry-core/src/utils.rs
- sentry-tower/src/http.rs
- sentry-tower/src/lib.rs
Follows the spec defined here: https://develop.sentry.dev/sdk/expected-features/data-handling/.
When `send-default-pii = true`, then capture all headers.
When `send-default-pii = false`, filter out sensitive headers.
Also send non-json/form request bodies when `send-default-pii=true`, as that's allowed according to spec.
I've deprecated the old `SentryHttpLayer::with_transaction` constructor so that this is not a breaking change in terms of API.
> refactor: honor `send_default_pii` in `sentry-actix` and `sentry-tower`

- sentry/src/transports/reqwest.rs
Adds a descriptive error message upon failure to create the `reqwest` client instead of unwrapping.
> feat(core): fail with message if TLS backend not available

- Cargo.toml
I forgot to add it in the previous PR, I guess craft will not work without it.
> build: add `sentry-opentelemetry` to workspace

- README.md
- sentry-opentelemetry/README.md
- sentry-opentelemetry/src/lib.rs
- sentry/README.md
- sentry/src/lib.rs
Adds docs for OTEL, basically what's already in `sentry-opentelemetry/src/lib.rs`.
Also mentions the `actix` and `tracing` integrations in the main README.md.
> docs: update docs including OTEL and other integrations

- sentry-actix/src/lib.rs
- sentry-core/src/clientoptions.rs
- sentry-core/src/session.rs
- sentry-opentelemetry/Cargo.toml
- sentry-tower/Cargo.toml
- sentry-tracing/Cargo.toml
- sentry/src/init.rs
Removes the `release-health` feature from `sentry-tower` and `sentry-tracing`, where it was used unnecessarily.
It's still a feature flag, enabled by default, in `sentry-actix`, as it's used there to create a session per request.
This was the default behavior previously, with no way of opting out, so it makes sense to keep it enabled by default there.
https://github.com/getsentry/sentry-rust/blob/3cc461a279d5a6ac45ea73268344d01318d8719e/sentry-actix/Cargo.toml#L16
I've fixed it to actually be used in the code because compilation would fail otherwise due to the `hub.start_session();` call.
There is no change to the `sentry` crate, where this flag is part of the default features as intended: https://github.com/getsentry/sentry-rust/blob/3cc461a279d5a6ac45ea73268344d01318d8719e/sentry/Cargo.t …
> fix: use `release-health` flag in `sentry-actix` and remove it from subcrates where unneeded

- sentry-opentelemetry/Cargo.toml
- sentry-opentelemetry/src/lib.rs
The doctests show usage from the point of view of the `sentry` crate, as we are importing the subcrate as `use sentry::integrations::opentelemetry as sentry_opentelemetry;`.
Therefore the first doctest will not compile.
The second will also not compile because we have the imports in the first.
Let's just use `ignore` on both of them.
> fix(otel): fix doctests

- CHANGELOG.md
Preparing the changelog for the upcoming release.
> chore: prepare changelog for 0.38 release

- CHANGELOG.md
- sentry-opentelemetry/Cargo.toml
See https://github.com/getsentry/publish/issues/740
> build(otel): exclude version from circular dev-dependencies

- CHANGELOG.md
- Cargo.lock
- sentry/Cargo.toml
Closes https://github.com/getsentry/sentry-rust/issues/804 
Closes https://github.com/getsentry/sentry-rust/issues/805
> build: pull in `sentry-actix` optionally when `release-health` is enabled

- .codecov.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/weekly.yml
- bump `actions/checkout` to `v4`
- bump`codecov/codecov-action` to `v5` and pass `secrets.CODECOV_TOKEN`
- move from `actions-rs/audit-check@v1` to `rustsec/audit-check@v2` (pinned) which is more or less maintained
> ci: bump actions, move to `rustsec/audit-check`

- Cargo.lock
- sentry-core/src/performance.rs
We have decided to not support parsing `traceparent` from incoming requests anymore, see https://github.com/getsentry/sentry-php/pull/1833 https://github.com/getsentry/sentry-docs/pull/13686
> refactor(core): remove support for `traceparent`

- .github/workflows/danger.yml
Enables Danger with our shared config.
I prefer to be forced to write the changelog directly with each PR.
> ci: adopt Danger with Sentry's shared config

- CHANGELOG.md
- sentry-core/Cargo.toml
- sentry-core/README.md
- sentry-core/src/lib.rs
- sentry-core/src/macros.rs
- sentry/Cargo.toml
- sentry/README.md
- sentry/src/lib.rs
Removes this feature that was already marked as deprecated.
This will allow us to use the `sentry_debug` macro in the other subcrates to log more stuff useful for troubleshooting.
Part of #620
> refactor: remove `debug-logs` feature

- CHANGELOG.md
- sentry-core/src/performance.rs
- sentry-core/src/scope/real.rs
- sentry-types/src/protocol/v7.rs
- sentry/tests/test_basic.rs
Implements Tracing without Performance ([spec](https://develop.sentry.dev/sdk/telemetry/traces/tracing-without-performance/)).
This is done by having an additional `PropagationContext` attribute on the scope that holds a "fake" `trace_id` and `span_id`.
When applying the scope to an event, if there is no ongoing span set on the scope, we create the `trace` context from the `PropagationContext`.
Additionally, adds an API `scope.iter_trace_propagation_headers` that should be preferred over something like:
```rust
sentry::configure_scope(|scope| {
if let Some(span) = scope.get_span() {
headers = Some(span.iter_headers());
} 
});
```
because it will use the `PropagationContext` as a fallback.
Closes #796
Also makes a minor adjustment to trace and span ids where we now use the `Display` impl …
> feat(core): implement Tracing without Performance

- CHANGELOG.md
- Cargo.lock
- sentry/Cargo.toml
- sentry/src/transports/ureq.rs
Update from ureq 2.x to 3.x. In ureq 3.x, rustls API is in itself not
exposed. That simplifies some of the TLS config. Furthermore the
webpki-roots are bundled and updated using patch-versions.
Close #834
> Update ureq to 3.x (#834)

- CHANGELOG.md
- sentry-tracing/Cargo.toml
- sentry-tracing/src/converters.rs
- sentry-tracing/src/layer.rs
- sentry-tracing/src/lib.rs
- sentry/tests/test_tracing.rs
- Refactor some code in preparation for the logs integration
- No breaking changes
- Improve the docs a little
- Test that a breadcrumb with errors carries the stringified error chain, behavior we added in https://github.com/getsentry/sentry-rust/pull/768
- It's also a behavioral change because we were previously attaching all error fields in an `errors` field in the JSON data of the breadcrumb, which doesn't make much sense. Now we'll store them in separate fields, retaining the original name
example:
```rust
tracing::info!(
database_error = &db_error as &dyn Error,
parse_error = &parse_error as &dyn Error,
retry_count = 3,
connection_timeout = "30s",
"Multiple errors occurred during database operation"
);
```
Before:
After:
> refactor(tracing): refactor internal code and improve docs

- CHANGELOG.md
- sentry-core/src/client.rs
- sentry-core/src/scope/real.rs
We have decided that SDKs should ignore `send_default_pii` when setting user attributes on logs because that's what we do for other data types such as events.
(explanation: any integration that can set the user must honor `send_default_pii`, so they won't set the user if that flag is off. Then, the only way to have a `user` on the scope is for the Sentry user to manually set it, in which case we always want to let them do it and send the data, regardless of `send_default_pii`.)
Technically this is a breaking change even though it's pretty unlikely that someone is already using this.
As an alternative we could just ignore the parameter.
> refactor(logs): apply user attributes to log regardless of `send_default_pii`

- CHANGELOG.md
- sentry-core/src/client.rs
- Cache default attributes and store them on the client
- They are always the same anyway. This way we clone once (from the cached attributes map to the actual log attributes) instead of doing multiple smaller clones.
- Add `os.name` and `os.version` attributes to the log, which are mandatory for native SDKs according to the spec, and personally I think they could be useful.
- The best way I've found to retrieve the OS context in `sentry-core` without making breaking changes or exposing additional API surface is the one I'm proposing, which still sucks.
> refactor(logs): cache default attributes and add OS attributes

- CHANGELOG.md
- sentry-types/src/protocol/v7.rs
- sentry-types/tests/test_protocol_v7.rs
Previously we were serializing these as floats which could lead to unnecessary precision loss.
Closes #845
> fix(logs): stringify u64 attributes greater than `i64::MAX`

- CHANGELOG.md
- Cargo.lock
- sentry-tracing/Cargo.toml
- sentry-tracing/src/converters.rs
- sentry-tracing/src/layer.rs
- sentry-tracing/src/lib.rs
- sentry/tests/test_tracing.rs
It seems common enough that someone would want to want to map  a `tracing` event to multiple item types, and right now that's not possible, you have to choose between Ignore/Event/Breadcrumb/Log.
For example, in Relay we want to send everything at or above INFO level to logs, while still sending ERROR events to Sentry events at the same time.
This is a proposal for how to implement that.
This particular solution requires 2 breaking changes, even though both could be avoided.
I would argue that they are not actually breaking for most users though, i.e. those that just set up a custom filter, as this is still backwards compatible in terms of syntax, even though the underlying type changes.
> feat(tracing): support combined EventFilters and EventMappings

- CHANGELOG.md
- Cargo.lock
- sentry-anyhow/Cargo.toml
Since anyhow 1.0.77, backtrace feature is not needed for Rust 1.65+ (https://github.com/dtolnay/anyhow/releases/tag/1.0.77). Because sentry has a higher MSRV than that, it's no longer necessary to enable this feature.
> chore(deps): bump `anyhow` and disable its `backtrace` feature

- sentry-tracing/src/lib.rs
This would need type annotations, so the doc test would fail to compile.
A way to fix it is to use the layer, so that the type is inferred.
> fix(tracing): fix doctest

- CHANGELOG.md
- sentry-log/Cargo.toml
- sentry-log/src/converters.rs
- sentry/tests/test_log.rs
- sentry/tests/test_log_logs.rs
Support for capturing key-value pairs from `log` with the `kv` feature as log attributes.
Also captures them on breadcrumbs and events.
Close https://github.com/getsentry/sentry-rust/issues/844
> feat(log): support kv feature of log

- sentry-types/src/protocol/envelope.rs
- sentry-types/src/protocol/v7.rs
- sentry-types/src/utils.rs
- sentry/src/transports/thread.rs
- sentry/src/transports/tokio_thread.rs
Adds the [documented envelope headers](https://develop.sentry.dev/sdk/data-model/envelopes/#envelope-headers) to the types.
In a separate PR we can start to populate the new values.
Closes https://github.com/getsentry/sentry-rust/issues/866
Required for https://github.com/getsentry/sentry-rust/issues/865
> feat(types): add all the missing supported envelope headers

- CHANGELOG.md
- sentry-actix/src/lib.rs
Before this change, if a middleware processing the request after the Sentry one returned an error, we would capture it unconditionally.
With this change, we capture it only if it's a server error.
(note that the behavior was correct for responses returned by services (i.e. request handler, not middleware), as at line 373 we check if it's a server error).
This is one of the possible ways to tackle this, and I think this is the one that makes most sense for the following reasons:
- Client errors could be spammy and don't usually provide much value to the user of Sentry.
- Capturing errors can be expensive when attaching stack traces.
- Better experience for new users that won't be surprised by this unintended behavior.
It must be said that there is a small possibility that someone misses …
> fix(actix): capture only server errors

- CHANGELOG.md
- sentry-tracing/src/converters.rs
Use the `code` attributes standardized in [OTEL](https://opentelemetry.io/docs/specs/semconv/registry/attributes/code/) to surface module, file and line info when creating logs out of `tracing` events, instead of using "custom" `tracing.<x>` ones.
> ref(tracing): use standard code attributes

- CHANGELOG.md
- sentry-types/src/protocol/attachment.rs
We would like to be able to send a custom attachment type, this makes it such that this is possible.
> feat(types): Add custom variant to `AttachmentType`
