src/lib.rs
so that users can handle panics with custom code
=> Add an Option<Fn> arg to register_panic_handler

src/lib.rs
This will be useful for other libs that depend on sentry
=> expose log function and support tags & extra fields

.travis.yml, Cargo.toml, Makefile, README.md, build.rs, src/api.rs, src/backtrace_support.rs, src/client/real.rs, src/constants.rs, src/integrations/error_chain.rs, src/integrations/failure.rs, src/integrations/log.rs, src/lib.rs, src/macros.rs, src/scope/noop.rs, src/scope/real.rs, src/transport.rs, src/utils.rs
Current nightly can't compiler one of our dependencies (or clippy).
=> ci: Run clippy as linter

Cargo.toml, examples/log-demo.rs, src/integrations/env_logger.rs, src/integrations/log.rs, src/integrations/mod.rs, src/lib.rs
=> feat: Added env_logger integration

Cargo.toml, examples/event-processors.rs, integrations/sentry-actix/Cargo.toml, integrations/sentry-actix/src/lib.rs, src/hub.rs, tests/test_threading.rs
This also removes an externally visible box.
=> ref: Switch to safe implementation of event processors

src/client.rs, src/hub.rs, src/utils.rs
This adds support for automatic stacktrace attachments to messages.  This is
disabled by default.
Fixes #64
=> feat: Added support for stacktrace attachments

Cargo.toml, integrations/sentry-actix/src/lib.rs, src/backtrace_support.rs, src/client.rs, src/constants.rs, src/hub.rs, src/integrations/error_chain.rs, src/integrations/failure.rs, src/integrations/log.rs, src/integrations/panic.rs, src/scope/real.rs, src/utils.rs, tests/test_basic.rs
This is somewhat blocked on https://github.com/getsentry/rust-sentry-types/issues/27
=> feat: Update to new sentry types

.travis.yml, Cargo.toml, Makefile, src/lib.rs, src/transport.rs
=> feat: Upgrade to reqwest 0.9

src/client.rs, tests/test_client.rs
=> feat: Added RefUnwindSafe for ClientOptions

Cargo.toml, src/backtrace_support.rs, src/lib.rs, src/utils.rs
This follows up on #112 
It's basically the same code with a small fix.
=> feat: Debug ID support for Linux

src/integrations/log.rs
See ordering of [LevelFilter](https://docs.rs/log/0.4.6/log/enum.LevelFilter.html)
=> fix(log): Report correct log_enabled

src/integrations/failure.rs, src/integrations/panic.rs
I thought i merged this already but evidently not.
=> feat: Add support for downcasting panics to failure errors

src/transport.rs
- Well behaved code should always name all spawned threads. It's to simplify debugging (`pstree -t PID`), the names are written to logs etc.
- `.unwrap()` may cause panic which is bad, but the same one was already in the original `thread::spawn()`. Fix would require API change which is out of scope of this update.
- Examples weren't touched to make them short and simple.
=> Name sender thread spawned by Sentry client.

src/transport.rs
The existing code might block the sending of events initially on low resolution clocks.
=> fix: Do not use the current timestamp as disabled-until

src/api.rs
Looks to be a classic left/right finger race condition ;)
=> Fix documentation typo in api.rs

.travis.yml, Cargo.toml, Makefile, examples/log-demo.rs, examples/thread-demo.rs, integrations/sentry-actix/src/lib.rs, src/backtrace_support.rs, src/hub.rs, src/integrations/failure.rs, src/scope/real.rs, src/transport.rs, src/utils.rs, tests/test_basic.rs
Aligns the makefile, updates dependencies and fixes clippy lints from Rust 1.34.0
=> ref: Update dependencies and dev env

.appveyor.yml, Cargo.toml
=> feat: Make openssl optional

src/integrations/env_logger.rs, src/integrations/log.rs
Functions that may panic should have the panics section
=> write the panics section for functions that may panic

Cargo.toml, src/transport.rs, tests/test_async.rs, tests/test_basic.rs
=> fix: Move reqwest init off the main thread

sentry-core/src/backtrace_support.rs, sentry-core/src/integrations/failure.rs
In preparation to split things up further.
=> ref: Move Backtrace parsing out of failure integration

sentry-core/src/backtrace_support.rs, sentry-core/src/client.rs, sentry-core/src/clientoptions.rs, sentry-core/src/hub.rs, sentry-core/src/integrations/mod.rs, sentry-core/src/lib.rs, sentry-core/src/transport.rs, sentry/src/defaults.rs
This takes a lot of inspiration from, and obsoletes #99, and is built on top of #199
=> feat: Create a simple Integration trait

README.tpl, scripts/bump-version.sh, scripts/generate-readme.sh, scripts/update-readme.sh, sentry-actix/README.md, sentry-actix/src/lib.rs, sentry-anyhow/README.md, sentry-anyhow/src/lib.rs, sentry-backtrace/README.md, sentry-backtrace/src/lib.rs, sentry-contexts/README.md, sentry-contexts/src/lib.rs, sentry-core/README.md, sentry-core/src/lib.rs, sentry-debug-images/README.md, sentry-debug-images/src/lib.rs, sentry-error-chain/README.md, sentry-error-chain/src/lib.rs, sentry-failure/README.md, sentry-failure/src/lib.rs, sentry-log/README.md, sentry-log/src/lib.rs, sentry-panic/README.md, sentry-panic/src/lib.rs, sentry-slog/README.md, sentry-slog/src/lib.rs, sentry-types/README.md, sentry-types/src/lib.rs, sentry/README.md, sentry/src/lib.rs
TODO as a followup: improve the crate docs of some sub-crates.
=> meta: Use cargo-readme to generate each crates README

sentry/Cargo.toml, sentry/src/transport.rs
=> fix: Update surf and unbreak CI

sentry-actix/Cargo.toml, sentry/Cargo.toml
Small oversight that I missed reviewing #282
=> fix: Clean up sentry-actix toml

CHANGELOG.md, sentry-slog/src/converters.rs, sentry-slog/src/lib.rs
I was a bit sloppy in review of #296 :-( , CC @jrobsonchase
=> fix: Properly document and test slog KV support

.github/workflows/ci.yml, .github/workflows/weekly.yml, sentry-actix/Cargo.toml, sentry-anyhow/Cargo.toml, sentry-backtrace/Cargo.toml, sentry-contexts/Cargo.toml, sentry-core/Cargo.toml, sentry-debug-images/Cargo.toml, sentry-panic/Cargo.toml, sentry-slog/Cargo.toml, sentry-types/Cargo.toml
Also cleans up the weekly clippy task as well
fixes #257
=> ci: Introduce a weekly audit task

sentry-actix/Cargo.toml, sentry-actix/src/lib.rs, sentry-core/src/session.rs, sentry-types/src/dsn.rs, sentry-types/src/macros.rs, sentry-types/src/protocol/v7.rs, sentry-types/src/utils.rs
- `Option` improvements
- Prefer `From` over `Into`
- Prefer `str::parse` over `$num::from_str_radix(X, 10)`
- Update `actix-rt` dev-dependency as a driveby
=> fix: Implement clippy nightly suggestions

sentry-debug-images/Cargo.toml, sentry-debug-images/src/images.rs
=> fix: Use the correct module_base for Windows Images

sentry-tracing/src/layer.rs
Otherwise, users cannot call `event_from_event(event, ctx)` from inside the custom event mapper.
=> Pass `ctx` to `event_mapper`

CHANGELOG.md, sentry-contexts/src/utils.rs, sentry-debug-images/src/images.rs, sentry-debug-images/src/lib.rs
wow, there has been a ton of contributors in this release
=> meta: Update changelog in preparation of release

sentry-contexts/build.rs, sentry-core/src/performance.rs, sentry/src/transports/curl.rs, sentry/src/transports/ureq.rs
=> ref: Pacify clippy

CHANGELOG.md, sentry/Cargo.toml
=> feat: Make debug-images a default feature

CHANGELOG.md
=> meta: Changelog for 0.30.0

sentry-core/src/profiling.rs
This closes the following [issue](https://github.com/orgs/getsentry/projects/30/views/7?pane=issue&itemId=18343664)
=> feat(profiling): remove a sample if it's the only sample in a thread

sentry-types/src/protocol/v7.rs
=> Derive Default on enums

CHANGELOG.md, Cargo.lock, sentry/Cargo.toml
Signed-off-by: Pierre Fenoll <pierrefenoll@gmail.com>
=> deps: upgrade reqwest to v0.12

sentry-actix/examples/basic.rs, sentry-actix/src/lib.rs
=> fix: fix clippy lints on stable

scripts/bump-version.sh
Update `Cargo.lock` automatically on release.
=> feat(scripts): add command to update `Cargo.lock`

sentry-log/src/converters.rs
=> chore: `cargo +stable clippy --fix`

sentry-actix/src/lib.rs, sentry-log/src/converters.rs, sentry-opentelemetry/src/processor.rs, sentry-tower/src/http.rs, sentry-tracing/src/layer.rs, sentry-tracing/tests/smoke.rs
=> feat: send trace origin
